// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="photon_trigger,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=1.953000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.339000,HLS_SYN_LAT=10239,HLS_SYN_TPT=none,HLS_SYN_MEM=194,HLS_SYN_DSP=0,HLS_SYN_FF=9984,HLS_SYN_LUT=9470,HLS_VERSION=2019_2_1}" *)

module photon_trigger (
        ap_clk,
        ap_rst_n,
        streamin_TDATA,
        streamin_TVALID,
        streamin_TREADY,
        streamin_TLAST,
        events_out_V_V_TDATA,
        events_out_V_V_TVALID,
        events_out_V_V_TREADY,
        timestamp_V,
        timestamp_V_ap_vld,
        timestamp_V_ap_ack,
        lane_V,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ctrl_clk,
        ap_rst_n_ctrl_clk
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 13;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] streamin_TDATA;
input   streamin_TVALID;
output   streamin_TREADY;
input   streamin_TLAST;
output  [111:0] events_out_V_V_TDATA;
output   events_out_V_V_TVALID;
input   events_out_V_V_TREADY;
input  [63:0] timestamp_V;
input   timestamp_V_ap_vld;
output   timestamp_V_ap_ack;
input  [1:0] lane_V;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ctrl_clk;
input   ap_rst_n_ctrl_clk;

reg streamin_TREADY;
reg timestamp_V_ap_ack;

 reg    ap_rst_n_inv;
wire   [8:0] triggercfg_0_threshold_V_address0;
reg    triggercfg_0_threshold_V_ce0;
wire   [15:0] triggercfg_0_threshold_V_q0;
wire   [8:0] triggercfg_1_threshold_V_address0;
reg    triggercfg_1_threshold_V_ce0;
wire   [15:0] triggercfg_1_threshold_V_q0;
wire   [8:0] triggercfg_2_threshold_V_address0;
reg    triggercfg_2_threshold_V_ce0;
wire   [15:0] triggercfg_2_threshold_V_q0;
wire   [8:0] triggercfg_3_threshold_V_address0;
reg    triggercfg_3_threshold_V_ce0;
wire   [15:0] triggercfg_3_threshold_V_q0;
wire   [9:0] holdoff_V;
wire   [8:0] baseline_shrink_V;
wire   [8:0] baseline_grow_V;
wire   [31:0] dropped;
reg   [1:0] next_out_V;
reg    streamin_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
reg    events_out_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg   [0:0] empty_n_reg_612;
reg    timestamp_V_blk_n;
reg    ap_rst_n_ctrl_clk_inv;
wire    ap_CS_fsm_state2;
wire   [0:0] ap_phi_mux_do_init_phi_fu_464_p6;
wire   [0:0] icmp_ln240_fu_809_p2;
reg   [0:0] icmp_ln240_reg_1260;
reg   [63:0] time_V_reg_1266;
reg    ap_block_state3;
wire    ap_CS_fsm_state11;
reg   [15:0] basedata_0_phase_V_reg_1291;
reg   [15:0] basedata_1_phase_V_reg_1296;
reg   [15:0] basedata_2_phase_V_reg_1301;
reg   [15:0] basedata_3_phase_V_reg_1306;
reg   [15:0] basedata_0_baseline_reg_1311;
reg   [15:0] basedata_1_baseline_reg_1316;
reg   [15:0] basedata_2_baseline_reg_1321;
reg   [15:0] basedata_3_baseline_reg_1326;
reg   [1:0] t_V_reg_1331;
wire    ap_CS_fsm_state17;
wire   [8:0] group_fu_993_p2;
reg   [8:0] group_reg_1337;
wire    ap_CS_fsm_state18;
wire   [63:0] event_time_V_fu_1055_p2;
reg   [63:0] event_time_V_reg_1382;
wire    ap_CS_fsm_state19;
wire   [0:0] ap_phi_mux_empty_n_phi_fu_615_p8;
wire   [0:0] icmp_ln851_fu_1065_p2;
reg   [0:0] icmp_ln851_reg_1387;
wire    grp_update_baselines_fu_626_ap_start;
wire    grp_update_baselines_fu_626_ap_done;
wire    grp_update_baselines_fu_626_ap_idle;
wire    grp_update_baselines_fu_626_ap_ready;
wire   [15:0] grp_update_baselines_fu_626_phases_0_V_read;
wire   [15:0] grp_update_baselines_fu_626_phases_1_V_read;
wire   [15:0] grp_update_baselines_fu_626_phases_2_V_read;
wire   [15:0] grp_update_baselines_fu_626_phases_3_V_read;
wire   [8:0] grp_update_baselines_fu_626_grow_n_V;
wire   [8:0] grp_update_baselines_fu_626_shrink_n_V;
wire   [15:0] grp_update_baselines_fu_626_ap_return_0;
wire   [15:0] grp_update_baselines_fu_626_ap_return_1;
wire   [15:0] grp_update_baselines_fu_626_ap_return_2;
wire   [15:0] grp_update_baselines_fu_626_ap_return_3;
wire   [15:0] grp_update_baselines_fu_626_ap_return_4;
wire   [15:0] grp_update_baselines_fu_626_ap_return_5;
wire   [15:0] grp_update_baselines_fu_626_ap_return_6;
wire   [15:0] grp_update_baselines_fu_626_ap_return_7;
wire    grp_analyze_pulse_fu_704_ap_start;
wire    grp_analyze_pulse_fu_704_ap_done;
wire    grp_analyze_pulse_fu_704_ap_idle;
wire    grp_analyze_pulse_fu_704_ap_ready;
wire    grp_analyze_pulse_fu_704_trigdata_0_trigger_s;
wire    grp_analyze_pulse_fu_704_trigdata_1_trigger_s;
wire    grp_analyze_pulse_fu_704_trigdata_2_trigger_s;
wire    grp_analyze_pulse_fu_704_trigdata_3_trigger_s;
wire   [124:0] grp_analyze_pulse_fu_704_pulsedata_V_0_din;
wire    grp_analyze_pulse_fu_704_pulsedata_V_0_write;
wire   [124:0] grp_analyze_pulse_fu_704_pulsedata_V_1_din;
wire    grp_analyze_pulse_fu_704_pulsedata_V_1_write;
wire   [124:0] grp_analyze_pulse_fu_704_pulsedata_V_2_din;
wire    grp_analyze_pulse_fu_704_pulsedata_V_2_write;
wire   [124:0] grp_analyze_pulse_fu_704_pulsedata_V_3_din;
wire    grp_analyze_pulse_fu_704_pulsedata_V_3_write;
wire   [15:0] grp_update_triggers_fu_789_ap_return_0;
wire   [15:0] grp_update_triggers_fu_789_ap_return_1;
wire   [15:0] grp_update_triggers_fu_789_ap_return_2;
wire   [15:0] grp_update_triggers_fu_789_ap_return_3;
wire   [15:0] grp_update_triggers_fu_789_ap_return_4;
wire   [15:0] grp_update_triggers_fu_789_ap_return_5;
wire   [15:0] grp_update_triggers_fu_789_ap_return_6;
wire   [15:0] grp_update_triggers_fu_789_ap_return_7;
wire   [0:0] grp_update_triggers_fu_789_ap_return_8;
wire   [0:0] grp_update_triggers_fu_789_ap_return_9;
wire   [0:0] grp_update_triggers_fu_789_ap_return_10;
wire   [0:0] grp_update_triggers_fu_789_ap_return_11;
reg   [0:0] do_init_reg_459;
wire    ap_CS_fsm_state1;
wire    regslice_both_events_out_V_V_U_apdone_blk;
reg    ap_block_state21_io;
wire   [0:0] icmp_ln234_fu_1220_p2;
reg   [9:0] holdoff_V4_phi_reg_550;
reg   [9:0] holdoff_V4_rewind_reg_475;
reg   [8:0] baseline_shrink_V5_p_reg_562;
reg   [8:0] baseline_shrink_V5_r_reg_490;
reg   [8:0] baseline_grow_V6_phi_reg_574;
reg   [8:0] baseline_grow_V6_rew_reg_505;
reg   [1:0] lane_V7_phi_reg_586;
reg   [1:0] lane_V7_rewind_reg_520;
reg   [8:0] val_assign3_reg_535;
reg   [124:0] tmp_0_reg_598;
reg    grp_update_baselines_fu_626_ap_start_reg;
reg   [20:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire   [8:0] select_ln240_fu_821_p3;
wire   [8:0] select_ln240_1_fu_829_p3;
reg    grp_analyze_pulse_fu_704_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_NS_fsm_state13;
wire    ap_CS_fsm_state13;
wire    pulsedata_V_0_full_n;
reg    pulsedata_V_0_write;
wire    ap_CS_fsm_state15;
wire    pulsedata_V_1_full_n;
reg    pulsedata_V_1_write;
wire    pulsedata_V_2_full_n;
reg    pulsedata_V_2_write;
wire    pulsedata_V_3_full_n;
reg    pulsedata_V_3_write;
wire   [63:0] zext_ln238_fu_889_p1;
wire   [1:0] add_ln700_fu_1209_p2;
reg   [8:0] p_095_05321_fu_330;
reg   [8:0] p_0327_05312_fu_334;
wire   [0:0] pulsedata_V_2_read_nbread_fu_376_p2_0;
wire   [124:0] pulsedata_V_2_dout;
wire    pulsedata_V_2_empty_n;
reg    pulsedata_V_2_read;
wire   [0:0] pulsedata_V_1_read_nbread_fu_382_p2_0;
wire   [124:0] pulsedata_V_1_dout;
wire    pulsedata_V_1_empty_n;
reg    pulsedata_V_1_read;
wire   [0:0] pulsedata_V_0_read_nbread_fu_388_p2_0;
wire   [124:0] pulsedata_V_0_dout;
wire    pulsedata_V_0_empty_n;
reg    pulsedata_V_0_read;
wire   [0:0] pulsedata_V_3_read_nbread_fu_394_p2_0;
wire   [124:0] pulsedata_V_3_dout;
wire    pulsedata_V_3_empty_n;
reg    pulsedata_V_3_read;
wire   [9:0] tmp_peak_time_V_load_fu_1041_p4;
wire   [63:0] zext_ln209_fu_1051_p1;
wire   [63:0] tmp_start_V_load_new_fu_1031_p4;
wire   [14:0] trunc_ln851_fu_1061_p1;
wire   [0:0] p_Result_s_fu_1089_p3;
wire   [0:0] ret_V_fu_1081_p3;
wire   [0:0] and_ln850_fu_1097_p2;
wire   [14:0] p_Result_5_fu_1124_p4;
wire   [0:0] p_Result_11_fu_1116_p3;
wire   [0:0] icmp_ln851_1_fu_1134_p2;
wire   [0:0] ret_V_1_fu_1108_p3;
wire   [0:0] and_ln850_1_fu_1140_p2;
wire   [0:0] xor_ln850_1_fu_1146_p2;
wire   [8:0] tmp_2_fu_1071_p4;
wire   [0:0] xor_ln850_fu_1102_p2;
wire   [92:0] select_ln1356_fu_1172_p3;
wire   [92:0] tmp_3_fu_1160_p6;
wire   [92:0] or_ln1356_fu_1180_p2;
wire   [93:0] tmp_9_fu_1186_p3;
wire  signed [96:0] sext_ln1356_fu_1194_p1;
wire   [96:0] select_ln1503_fu_1152_p3;
wire   [96:0] ret_V_3_fu_1198_p2;
wire    regslice_both_streamin_data_V_U_apdone_blk;
wire   [63:0] streamin_TDATA_int;
wire    streamin_TVALID_int;
reg    streamin_TREADY_int;
wire    regslice_both_streamin_data_V_U_ack_in;
wire    regslice_both_w1_streamin_last_U_apdone_blk;
wire    streamin_TLAST_int;
wire    regslice_both_w1_streamin_last_U_vld_out;
wire    regslice_both_w1_streamin_last_U_ack_in;
wire   [111:0] events_out_V_V_TDATA_int;
reg    events_out_V_V_TVALID_int;
wire    events_out_V_V_TREADY_int;
wire    regslice_both_events_out_V_V_U_vld_out;

// power-on initialization
initial begin
#0 next_out_V = 2'd0;
#0 ap_CS_fsm = 21'd1;
#0 grp_update_baselines_fu_626_ap_start_reg = 1'b0;
#0 grp_analyze_pulse_fu_704_ap_start_reg = 1'b0;
end

photon_trigger_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
photon_trigger_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ctrl_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .triggercfg_0_threshold_V_address0(triggercfg_0_threshold_V_address0),
    .triggercfg_0_threshold_V_ce0(triggercfg_0_threshold_V_ce0),
    .triggercfg_0_threshold_V_q0(triggercfg_0_threshold_V_q0),
    .triggercfg_1_threshold_V_address0(triggercfg_1_threshold_V_address0),
    .triggercfg_1_threshold_V_ce0(triggercfg_1_threshold_V_ce0),
    .triggercfg_1_threshold_V_q0(triggercfg_1_threshold_V_q0),
    .triggercfg_2_threshold_V_address0(triggercfg_2_threshold_V_address0),
    .triggercfg_2_threshold_V_ce0(triggercfg_2_threshold_V_ce0),
    .triggercfg_2_threshold_V_q0(triggercfg_2_threshold_V_q0),
    .triggercfg_3_threshold_V_address0(triggercfg_3_threshold_V_address0),
    .triggercfg_3_threshold_V_ce0(triggercfg_3_threshold_V_ce0),
    .triggercfg_3_threshold_V_q0(triggercfg_3_threshold_V_q0),
    .holdoff_V(holdoff_V),
    .baseline_shrink_V(baseline_shrink_V),
    .baseline_grow_V(baseline_grow_V),
    .dropped(dropped),
    .clk(ap_clk),
    .rst(ap_rst_n_ctrl_clk_inv)
);

update_baselines grp_update_baselines_fu_626(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_update_baselines_fu_626_ap_start),
    .ap_done(grp_update_baselines_fu_626_ap_done),
    .ap_idle(grp_update_baselines_fu_626_ap_idle),
    .ap_ready(grp_update_baselines_fu_626_ap_ready),
    .group_V(val_assign3_reg_535),
    .phases_0_V_read(grp_update_baselines_fu_626_phases_0_V_read),
    .phases_1_V_read(grp_update_baselines_fu_626_phases_1_V_read),
    .phases_2_V_read(grp_update_baselines_fu_626_phases_2_V_read),
    .phases_3_V_read(grp_update_baselines_fu_626_phases_3_V_read),
    .grow_n_V(grp_update_baselines_fu_626_grow_n_V),
    .shrink_n_V(grp_update_baselines_fu_626_shrink_n_V),
    .ap_return_0(grp_update_baselines_fu_626_ap_return_0),
    .ap_return_1(grp_update_baselines_fu_626_ap_return_1),
    .ap_return_2(grp_update_baselines_fu_626_ap_return_2),
    .ap_return_3(grp_update_baselines_fu_626_ap_return_3),
    .ap_return_4(grp_update_baselines_fu_626_ap_return_4),
    .ap_return_5(grp_update_baselines_fu_626_ap_return_5),
    .ap_return_6(grp_update_baselines_fu_626_ap_return_6),
    .ap_return_7(grp_update_baselines_fu_626_ap_return_7)
);

analyze_pulse grp_analyze_pulse_fu_704(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_analyze_pulse_fu_704_ap_start),
    .ap_done(grp_analyze_pulse_fu_704_ap_done),
    .ap_idle(grp_analyze_pulse_fu_704_ap_idle),
    .ap_ready(grp_analyze_pulse_fu_704_ap_ready),
    .group_V(val_assign3_reg_535),
    .trigdata_0_phase_V_s(grp_update_triggers_fu_789_ap_return_0),
    .trigdata_1_phase_V_s(grp_update_triggers_fu_789_ap_return_1),
    .trigdata_2_phase_V_s(grp_update_triggers_fu_789_ap_return_2),
    .trigdata_3_phase_V_s(grp_update_triggers_fu_789_ap_return_3),
    .trigdata_0_baseline(grp_update_triggers_fu_789_ap_return_4),
    .trigdata_1_baseline(grp_update_triggers_fu_789_ap_return_5),
    .trigdata_2_baseline(grp_update_triggers_fu_789_ap_return_6),
    .trigdata_3_baseline(grp_update_triggers_fu_789_ap_return_7),
    .trigdata_0_trigger_s(grp_analyze_pulse_fu_704_trigdata_0_trigger_s),
    .trigdata_1_trigger_s(grp_analyze_pulse_fu_704_trigdata_1_trigger_s),
    .trigdata_2_trigger_s(grp_analyze_pulse_fu_704_trigdata_2_trigger_s),
    .trigdata_3_trigger_s(grp_analyze_pulse_fu_704_trigdata_3_trigger_s),
    .holdoff_V(holdoff_V4_phi_reg_550),
    .timestamp_V(time_V_reg_1266),
    .pulsedata_V_0_din(grp_analyze_pulse_fu_704_pulsedata_V_0_din),
    .pulsedata_V_0_full_n(pulsedata_V_0_full_n),
    .pulsedata_V_0_write(grp_analyze_pulse_fu_704_pulsedata_V_0_write),
    .pulsedata_V_1_din(grp_analyze_pulse_fu_704_pulsedata_V_1_din),
    .pulsedata_V_1_full_n(pulsedata_V_1_full_n),
    .pulsedata_V_1_write(grp_analyze_pulse_fu_704_pulsedata_V_1_write),
    .pulsedata_V_2_din(grp_analyze_pulse_fu_704_pulsedata_V_2_din),
    .pulsedata_V_2_full_n(pulsedata_V_2_full_n),
    .pulsedata_V_2_write(grp_analyze_pulse_fu_704_pulsedata_V_2_write),
    .pulsedata_V_3_din(grp_analyze_pulse_fu_704_pulsedata_V_3_din),
    .pulsedata_V_3_full_n(pulsedata_V_3_full_n),
    .pulsedata_V_3_write(grp_analyze_pulse_fu_704_pulsedata_V_3_write)
);

update_triggers grp_update_triggers_fu_789(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_0_phase_V_read(basedata_0_phase_V_reg_1291),
    .data_1_phase_V_read(basedata_1_phase_V_reg_1296),
    .data_2_phase_V_read(basedata_2_phase_V_reg_1301),
    .data_3_phase_V_read(basedata_3_phase_V_reg_1306),
    .data_0_baseline_V_r(basedata_0_baseline_reg_1311),
    .data_1_baseline_V_r(basedata_1_baseline_reg_1316),
    .data_2_baseline_V_r(basedata_2_baseline_reg_1321),
    .data_3_baseline_V_r(basedata_3_baseline_reg_1326),
    .trig_cfg_0_threshol(triggercfg_0_threshold_V_q0),
    .trig_cfg_1_threshol(triggercfg_1_threshold_V_q0),
    .trig_cfg_2_threshol(triggercfg_2_threshold_V_q0),
    .trig_cfg_3_threshol(triggercfg_3_threshold_V_q0),
    .ap_return_0(grp_update_triggers_fu_789_ap_return_0),
    .ap_return_1(grp_update_triggers_fu_789_ap_return_1),
    .ap_return_2(grp_update_triggers_fu_789_ap_return_2),
    .ap_return_3(grp_update_triggers_fu_789_ap_return_3),
    .ap_return_4(grp_update_triggers_fu_789_ap_return_4),
    .ap_return_5(grp_update_triggers_fu_789_ap_return_5),
    .ap_return_6(grp_update_triggers_fu_789_ap_return_6),
    .ap_return_7(grp_update_triggers_fu_789_ap_return_7),
    .ap_return_8(grp_update_triggers_fu_789_ap_return_8),
    .ap_return_9(grp_update_triggers_fu_789_ap_return_9),
    .ap_return_10(grp_update_triggers_fu_789_ap_return_10),
    .ap_return_11(grp_update_triggers_fu_789_ap_return_11)
);

fifo_w125_d64_A pulsedata_V_0_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_analyze_pulse_fu_704_pulsedata_V_0_din),
    .if_full_n(pulsedata_V_0_full_n),
    .if_write(pulsedata_V_0_write),
    .if_dout(pulsedata_V_0_dout),
    .if_empty_n(pulsedata_V_0_empty_n),
    .if_read(pulsedata_V_0_read)
);

fifo_w125_d64_A pulsedata_V_1_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_analyze_pulse_fu_704_pulsedata_V_1_din),
    .if_full_n(pulsedata_V_1_full_n),
    .if_write(pulsedata_V_1_write),
    .if_dout(pulsedata_V_1_dout),
    .if_empty_n(pulsedata_V_1_empty_n),
    .if_read(pulsedata_V_1_read)
);

fifo_w125_d64_A pulsedata_V_2_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_analyze_pulse_fu_704_pulsedata_V_2_din),
    .if_full_n(pulsedata_V_2_full_n),
    .if_write(pulsedata_V_2_write),
    .if_dout(pulsedata_V_2_dout),
    .if_empty_n(pulsedata_V_2_empty_n),
    .if_read(pulsedata_V_2_read)
);

fifo_w125_d64_A pulsedata_V_3_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_analyze_pulse_fu_704_pulsedata_V_3_din),
    .if_full_n(pulsedata_V_3_full_n),
    .if_write(pulsedata_V_3_write),
    .if_dout(pulsedata_V_3_dout),
    .if_empty_n(pulsedata_V_3_empty_n),
    .if_read(pulsedata_V_3_read)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_streamin_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(streamin_TDATA),
    .vld_in(streamin_TVALID),
    .ack_in(regslice_both_streamin_data_V_U_ack_in),
    .data_out(streamin_TDATA_int),
    .vld_out(streamin_TVALID_int),
    .ack_out(streamin_TREADY_int),
    .apdone_blk(regslice_both_streamin_data_V_U_apdone_blk)
);

regslice_both_w1 #(
    .DataWidth( 1 ))
regslice_both_w1_streamin_last_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(streamin_TLAST),
    .vld_in(streamin_TVALID),
    .ack_in(regslice_both_w1_streamin_last_U_ack_in),
    .data_out(streamin_TLAST_int),
    .vld_out(regslice_both_w1_streamin_last_U_vld_out),
    .ack_out(streamin_TREADY_int),
    .apdone_blk(regslice_both_w1_streamin_last_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 112 ))
regslice_both_events_out_V_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(events_out_V_V_TDATA_int),
    .vld_in(events_out_V_V_TVALID_int),
    .ack_in(events_out_V_V_TREADY_int),
    .data_out(events_out_V_V_TDATA),
    .vld_out(regslice_both_events_out_V_V_U_vld_out),
    .ack_out(events_out_V_V_TREADY),
    .apdone_blk(regslice_both_events_out_V_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_analyze_pulse_fu_704_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state13) & (1'b1 == ap_CS_fsm_state12))) begin
            grp_analyze_pulse_fu_704_ap_start_reg <= 1'b1;
        end else if ((grp_analyze_pulse_fu_704_ap_ready == 1'b1)) begin
            grp_analyze_pulse_fu_704_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_update_baselines_fu_626_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_update_baselines_fu_626_ap_start_reg <= 1'b1;
        end else if ((grp_update_baselines_fu_626_ap_ready == 1'b1)) begin
            grp_update_baselines_fu_626_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd0)) begin
            baseline_grow_V6_phi_reg_574 <= baseline_grow_V6_rew_reg_505;
        end else if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd1)) begin
            baseline_grow_V6_phi_reg_574 <= baseline_grow_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd0)) begin
            baseline_shrink_V5_p_reg_562 <= baseline_shrink_V5_r_reg_490;
        end else if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd1)) begin
            baseline_shrink_V5_p_reg_562 <= baseline_shrink_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (icmp_ln234_fu_1220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        do_init_reg_459 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state1) | (~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (icmp_ln234_fu_1220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21)))) begin
        do_init_reg_459 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((t_V_reg_1331 == 2'd0)) begin
            empty_n_reg_612 <= pulsedata_V_0_read_nbread_fu_388_p2_0;
        end else if ((t_V_reg_1331 == 2'd1)) begin
            empty_n_reg_612 <= pulsedata_V_1_read_nbread_fu_382_p2_0;
        end else if ((t_V_reg_1331 == 2'd2)) begin
            empty_n_reg_612 <= pulsedata_V_2_read_nbread_fu_376_p2_0;
        end else if ((t_V_reg_1331 == 2'd3)) begin
            empty_n_reg_612 <= pulsedata_V_3_read_nbread_fu_394_p2_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd0)) begin
            holdoff_V4_phi_reg_550 <= holdoff_V4_rewind_reg_475;
        end else if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd1)) begin
            holdoff_V4_phi_reg_550 <= holdoff_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd0)) begin
            lane_V7_phi_reg_586 <= lane_V7_rewind_reg_520;
        end else if ((ap_phi_mux_do_init_phi_fu_464_p6 == 1'd1)) begin
            lane_V7_phi_reg_586 <= lane_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((t_V_reg_1331 == 2'd0)) begin
            tmp_0_reg_598 <= pulsedata_V_0_dout;
        end else if ((t_V_reg_1331 == 2'd1)) begin
            tmp_0_reg_598 <= pulsedata_V_1_dout;
        end else if ((t_V_reg_1331 == 2'd2)) begin
            tmp_0_reg_598 <= pulsedata_V_2_dout;
        end else if ((t_V_reg_1331 == 2'd3)) begin
            tmp_0_reg_598 <= pulsedata_V_3_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (icmp_ln234_fu_1220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        val_assign3_reg_535 <= group_reg_1337;
    end else if (((1'b1 == ap_CS_fsm_state1) | (~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (icmp_ln234_fu_1220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21)))) begin
        val_assign3_reg_535 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        basedata_0_baseline_reg_1311 <= grp_update_baselines_fu_626_ap_return_4;
        basedata_0_phase_V_reg_1291 <= grp_update_baselines_fu_626_ap_return_0;
        basedata_1_baseline_reg_1316 <= grp_update_baselines_fu_626_ap_return_5;
        basedata_1_phase_V_reg_1296 <= grp_update_baselines_fu_626_ap_return_1;
        basedata_2_baseline_reg_1321 <= grp_update_baselines_fu_626_ap_return_6;
        basedata_2_phase_V_reg_1301 <= grp_update_baselines_fu_626_ap_return_2;
        basedata_3_baseline_reg_1326 <= grp_update_baselines_fu_626_ap_return_7;
        basedata_3_phase_V_reg_1306 <= grp_update_baselines_fu_626_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (icmp_ln234_fu_1220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        baseline_grow_V6_rew_reg_505 <= baseline_grow_V6_phi_reg_574;
        baseline_shrink_V5_r_reg_490 <= baseline_shrink_V5_p_reg_562;
        holdoff_V4_rewind_reg_475 <= holdoff_V4_phi_reg_550;
        lane_V7_rewind_reg_520 <= lane_V7_phi_reg_586;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_empty_n_phi_fu_615_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        event_time_V_reg_1382 <= event_time_V_fu_1055_p2;
        icmp_ln851_reg_1387 <= icmp_ln851_fu_1065_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        group_reg_1337 <= group_fu_993_p2;
        t_V_reg_1331 <= next_out_V;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln240_reg_1260 <= icmp_ln240_fu_809_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state21))) begin
        next_out_V <= add_ln700_fu_1209_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((timestamp_V_ap_vld == 1'b0) | (streamin_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0327_05312_fu_334 <= select_ln240_1_fu_829_p3;
        p_095_05321_fu_330 <= select_ln240_fu_821_p3;
        time_V_reg_1266 <= timestamp_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((empty_n_reg_612 == 1'd1) & (1'b1 == ap_CS_fsm_state21)))) begin
        events_out_V_V_TDATA_blk_n = events_out_V_V_TREADY_int;
    end else begin
        events_out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (events_out_V_V_TREADY_int == 1'b1))) begin
        events_out_V_V_TVALID_int = 1'b1;
    end else begin
        events_out_V_V_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    if (((t_V_reg_1331 == 2'd0) & (pulsedata_V_0_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        pulsedata_V_0_read = 1'b1;
    end else begin
        pulsedata_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        pulsedata_V_0_write = grp_analyze_pulse_fu_704_pulsedata_V_0_write;
    end else begin
        pulsedata_V_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((pulsedata_V_1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18) & (t_V_reg_1331 == 2'd1))) begin
        pulsedata_V_1_read = 1'b1;
    end else begin
        pulsedata_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        pulsedata_V_1_write = grp_analyze_pulse_fu_704_pulsedata_V_1_write;
    end else begin
        pulsedata_V_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((pulsedata_V_2_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18) & (t_V_reg_1331 == 2'd2))) begin
        pulsedata_V_2_read = 1'b1;
    end else begin
        pulsedata_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        pulsedata_V_2_write = grp_analyze_pulse_fu_704_pulsedata_V_2_write;
    end else begin
        pulsedata_V_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((pulsedata_V_3_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18) & (t_V_reg_1331 == 2'd3))) begin
        pulsedata_V_3_read = 1'b1;
    end else begin
        pulsedata_V_3_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        pulsedata_V_3_write = grp_analyze_pulse_fu_704_pulsedata_V_3_write;
    end else begin
        pulsedata_V_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        streamin_TDATA_blk_n = streamin_TVALID_int;
    end else begin
        streamin_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((streamin_TVALID == 1'b1) & (regslice_both_streamin_data_V_U_ack_in == 1'b1))) begin
        streamin_TREADY = 1'b1;
    end else begin
        streamin_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((timestamp_V_ap_vld == 1'b0) | (streamin_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        streamin_TREADY_int = 1'b1;
    end else begin
        streamin_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((timestamp_V_ap_vld == 1'b0) | (streamin_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        timestamp_V_ap_ack = 1'b1;
    end else begin
        timestamp_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        timestamp_V_blk_n = timestamp_V_ap_vld;
    end else begin
        timestamp_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        triggercfg_0_threshold_V_ce0 = 1'b1;
    end else begin
        triggercfg_0_threshold_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        triggercfg_1_threshold_V_ce0 = 1'b1;
    end else begin
        triggercfg_1_threshold_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        triggercfg_2_threshold_V_ce0 = 1'b1;
    end else begin
        triggercfg_2_threshold_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        triggercfg_3_threshold_V_ce0 = 1'b1;
    end else begin
        triggercfg_3_threshold_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((timestamp_V_ap_vld == 1'b0) | (streamin_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((ap_phi_mux_empty_n_phi_fu_615_p8 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (events_out_V_V_TREADY_int == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if ((~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (icmp_ln234_fu_1220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((1'b1 == ap_block_state21_io) | (regslice_both_events_out_V_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln700_fu_1209_p2 = (t_V_reg_1331 + 2'd1);

assign and_ln850_1_fu_1140_p2 = (p_Result_11_fu_1116_p3 & icmp_ln851_1_fu_1134_p2);

assign and_ln850_fu_1097_p2 = (p_Result_s_fu_1089_p3 & icmp_ln851_reg_1387);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state13 = ap_NS_fsm[32'd12];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state21_io = ((empty_n_reg_612 == 1'd1) & (events_out_V_V_TREADY_int == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((timestamp_V_ap_vld == 1'b0) | (streamin_TVALID_int == 1'b0));
end

assign ap_phi_mux_do_init_phi_fu_464_p6 = do_init_reg_459;

assign ap_phi_mux_empty_n_phi_fu_615_p8 = empty_n_reg_612;

always @ (*) begin
    ap_rst_n_ctrl_clk_inv = ~ap_rst_n_ctrl_clk;
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign event_time_V_fu_1055_p2 = (zext_ln209_fu_1051_p1 + tmp_start_V_load_new_fu_1031_p4);

assign events_out_V_V_TDATA_int = $signed(ret_V_3_fu_1198_p2);

assign events_out_V_V_TVALID = regslice_both_events_out_V_V_U_vld_out;

assign group_fu_993_p2 = (9'd1 + val_assign3_reg_535);

assign grp_analyze_pulse_fu_704_ap_start = grp_analyze_pulse_fu_704_ap_start_reg;

assign grp_analyze_pulse_fu_704_trigdata_0_trigger_s = grp_update_triggers_fu_789_ap_return_8;

assign grp_analyze_pulse_fu_704_trigdata_1_trigger_s = grp_update_triggers_fu_789_ap_return_9;

assign grp_analyze_pulse_fu_704_trigdata_2_trigger_s = grp_update_triggers_fu_789_ap_return_10;

assign grp_analyze_pulse_fu_704_trigdata_3_trigger_s = grp_update_triggers_fu_789_ap_return_11;

assign grp_update_baselines_fu_626_ap_start = grp_update_baselines_fu_626_ap_start_reg;

assign grp_update_baselines_fu_626_grow_n_V = ((icmp_ln240_reg_1260[0:0] === 1'b1) ? baseline_grow_V6_phi_reg_574 : p_095_05321_fu_330);

assign grp_update_baselines_fu_626_phases_0_V_read = streamin_TDATA_int[15:0];

assign grp_update_baselines_fu_626_phases_1_V_read = {{streamin_TDATA_int[31:16]}};

assign grp_update_baselines_fu_626_phases_2_V_read = {{streamin_TDATA_int[47:32]}};

assign grp_update_baselines_fu_626_phases_3_V_read = {{streamin_TDATA_int[63:48]}};

assign grp_update_baselines_fu_626_shrink_n_V = ((icmp_ln240_reg_1260[0:0] === 1'b1) ? baseline_shrink_V5_p_reg_562 : p_0327_05312_fu_334);

assign icmp_ln234_fu_1220_p2 = ((val_assign3_reg_535 == 9'd511) ? 1'b1 : 1'b0);

assign icmp_ln240_fu_809_p2 = ((val_assign3_reg_535 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_1_fu_1134_p2 = ((p_Result_5_fu_1124_p4 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_fu_1065_p2 = ((trunc_ln851_fu_1061_p1 != 15'd0) ? 1'b1 : 1'b0);

assign or_ln1356_fu_1180_p2 = (tmp_3_fu_1160_p6 | select_ln1356_fu_1172_p3);

assign p_Result_11_fu_1116_p3 = tmp_0_reg_598[32'd124];

assign p_Result_5_fu_1124_p4 = {{tmp_0_reg_598[123:109]}};

assign p_Result_s_fu_1089_p3 = tmp_0_reg_598[32'd15];

assign pulsedata_V_0_read_nbread_fu_388_p2_0 = pulsedata_V_0_empty_n;

assign pulsedata_V_1_read_nbread_fu_382_p2_0 = pulsedata_V_1_empty_n;

assign pulsedata_V_2_read_nbread_fu_376_p2_0 = pulsedata_V_2_empty_n;

assign pulsedata_V_3_read_nbread_fu_394_p2_0 = pulsedata_V_3_empty_n;

assign ret_V_1_fu_1108_p3 = tmp_0_reg_598[32'd124];

assign ret_V_3_fu_1198_p2 = (sext_ln1356_fu_1194_p1 | select_ln1503_fu_1152_p3);

assign ret_V_fu_1081_p3 = tmp_0_reg_598[32'd15];

assign select_ln1356_fu_1172_p3 = ((xor_ln850_fu_1102_p2[0:0] === 1'b1) ? 93'd9903520295836298125483442176 : 93'd0);

assign select_ln1503_fu_1152_p3 = ((xor_ln850_1_fu_1146_p2[0:0] === 1'b1) ? 97'd79228162514264337593543950336 : 97'd0);

assign select_ln240_1_fu_829_p3 = ((icmp_ln240_reg_1260[0:0] === 1'b1) ? baseline_shrink_V5_p_reg_562 : p_0327_05312_fu_334);

assign select_ln240_fu_821_p3 = ((icmp_ln240_reg_1260[0:0] === 1'b1) ? baseline_grow_V6_phi_reg_574 : p_095_05321_fu_330);

assign sext_ln1356_fu_1194_p1 = $signed(tmp_9_fu_1186_p3);

assign tmp_2_fu_1071_p4 = {{tmp_0_reg_598[24:16]}};

assign tmp_3_fu_1160_p6 = {{{{{lane_V7_phi_reg_586}, {tmp_2_fu_1071_p4}}, {t_V_reg_1331}}, {16'd0}}, {event_time_V_reg_1382}};

assign tmp_9_fu_1186_p3 = {{xor_ln850_fu_1102_p2}, {or_ln1356_fu_1180_p2}};

assign tmp_peak_time_V_load_fu_1041_p4 = {{tmp_0_reg_598[98:89]}};

assign tmp_start_V_load_new_fu_1031_p4 = {{tmp_0_reg_598[88:25]}};

assign triggercfg_0_threshold_V_address0 = zext_ln238_fu_889_p1;

assign triggercfg_1_threshold_V_address0 = zext_ln238_fu_889_p1;

assign triggercfg_2_threshold_V_address0 = zext_ln238_fu_889_p1;

assign triggercfg_3_threshold_V_address0 = zext_ln238_fu_889_p1;

assign trunc_ln851_fu_1061_p1 = tmp_0_reg_598[14:0];

assign xor_ln850_1_fu_1146_p2 = (ret_V_1_fu_1108_p3 ^ and_ln850_1_fu_1140_p2);

assign xor_ln850_fu_1102_p2 = (ret_V_fu_1081_p3 ^ and_ln850_fu_1097_p2);

assign zext_ln209_fu_1051_p1 = tmp_peak_time_V_load_fu_1041_p4;

assign zext_ln238_fu_889_p1 = val_assign3_reg_535;

endmodule //photon_trigger
