-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity photon_trigger is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 13;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    streamin_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    streamin_TVALID : IN STD_LOGIC;
    streamin_TREADY : OUT STD_LOGIC;
    streamin_TLAST : IN STD_LOGIC;
    events_out_V_din : OUT STD_LOGIC_VECTOR (111 downto 0);
    events_out_V_full_n : IN STD_LOGIC;
    events_out_V_write : OUT STD_LOGIC;
    timestamp_V : IN STD_LOGIC_VECTOR (63 downto 0);
    timestamp_V_ap_vld : IN STD_LOGIC;
    timestamp_V_ap_ack : OUT STD_LOGIC;
    lane_V : IN STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of photon_trigger is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "photon_trigger,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=1.953000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.339000,HLS_SYN_LAT=10239,HLS_SYN_TPT=none,HLS_SYN_MEM=194,HLS_SYN_DSP=0,HLS_SYN_FF=10126,HLS_SYN_LUT=8798,HLS_VERSION=2019_2_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (20 downto 0) := "000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (20 downto 0) := "000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (20 downto 0) := "000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (20 downto 0) := "000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (20 downto 0) := "000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (20 downto 0) := "000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (20 downto 0) := "000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (20 downto 0) := "000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (20 downto 0) := "000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (20 downto 0) := "001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (20 downto 0) := "010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (20 downto 0) := "100000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv8_1F : STD_LOGIC_VECTOR (7 downto 0) := "00011111";
    constant ap_const_lv8_20 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_const_lv8_2F : STD_LOGIC_VECTOR (7 downto 0) := "00101111";
    constant ap_const_lv8_30 : STD_LOGIC_VECTOR (7 downto 0) := "00110000";
    constant ap_const_lv8_3F : STD_LOGIC_VECTOR (7 downto 0) := "00111111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_7C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111100";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal triggercfg_0_threshold_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal triggercfg_0_threshold_V_ce0 : STD_LOGIC;
    signal triggercfg_0_threshold_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal triggercfg_1_threshold_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal triggercfg_1_threshold_V_ce0 : STD_LOGIC;
    signal triggercfg_1_threshold_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal triggercfg_2_threshold_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal triggercfg_2_threshold_V_ce0 : STD_LOGIC;
    signal triggercfg_2_threshold_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal triggercfg_3_threshold_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal triggercfg_3_threshold_V_ce0 : STD_LOGIC;
    signal triggercfg_3_threshold_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal holdoff_V : STD_LOGIC_VECTOR (9 downto 0);
    signal baseline_shrink_V : STD_LOGIC_VECTOR (8 downto 0);
    signal baseline_grow_V : STD_LOGIC_VECTOR (8 downto 0);
    signal dropped_i : STD_LOGIC_VECTOR (31 downto 0);
    signal dropped_o_ap_vld : STD_LOGIC;
    signal next_out_V : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal streamin_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal timestamp_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_phi_mux_do_init_phi_fu_459_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln239_fu_803_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln239_reg_1161 : STD_LOGIC_VECTOR (0 downto 0);
    signal time_V_reg_1167 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal basedata_0_phase_V_reg_1192 : STD_LOGIC_VECTOR (15 downto 0);
    signal basedata_1_phase_V_reg_1197 : STD_LOGIC_VECTOR (15 downto 0);
    signal basedata_2_phase_V_reg_1202 : STD_LOGIC_VECTOR (15 downto 0);
    signal basedata_3_phase_V_reg_1207 : STD_LOGIC_VECTOR (15 downto 0);
    signal basedata_0_baseline_reg_1212 : STD_LOGIC_VECTOR (15 downto 0);
    signal basedata_1_baseline_reg_1217 : STD_LOGIC_VECTOR (15 downto 0);
    signal basedata_2_baseline_reg_1222 : STD_LOGIC_VECTOR (15 downto 0);
    signal basedata_3_baseline_reg_1227 : STD_LOGIC_VECTOR (15 downto 0);
    signal t_V_reg_1232 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal group_fu_987_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal group_reg_1238 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal event_phase_V_fu_1025_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal event_phase_V_reg_1283 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal event_baseline_V_reg_1288 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_reg_1293 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_empty_n_phi_fu_609_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal event_time_V_fu_1073_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal event_time_V_reg_1298 : STD_LOGIC_VECTOR (63 downto 0);
    signal dropped_read_reg_1303 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln262_fu_1105_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln262_reg_1308 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_update_baselines_fu_620_ap_start : STD_LOGIC;
    signal grp_update_baselines_fu_620_ap_done : STD_LOGIC;
    signal grp_update_baselines_fu_620_ap_idle : STD_LOGIC;
    signal grp_update_baselines_fu_620_ap_ready : STD_LOGIC;
    signal grp_update_baselines_fu_620_phases_0_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_phases_1_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_phases_2_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_phases_3_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_grow_n_V : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_update_baselines_fu_620_shrink_n_V : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_update_baselines_fu_620_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_baselines_fu_620_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_analyze_pulse_fu_698_ap_start : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_ap_done : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_ap_idle : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_ap_ready : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_trigdata_0_trigger_s : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_trigdata_1_trigger_s : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_trigdata_2_trigger_s : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_trigdata_3_trigger_s : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_pulsedata_V_0_din : STD_LOGIC_VECTOR (124 downto 0);
    signal grp_analyze_pulse_fu_698_pulsedata_V_0_write : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_pulsedata_V_1_din : STD_LOGIC_VECTOR (124 downto 0);
    signal grp_analyze_pulse_fu_698_pulsedata_V_1_write : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_pulsedata_V_2_din : STD_LOGIC_VECTOR (124 downto 0);
    signal grp_analyze_pulse_fu_698_pulsedata_V_2_write : STD_LOGIC;
    signal grp_analyze_pulse_fu_698_pulsedata_V_3_din : STD_LOGIC_VECTOR (124 downto 0);
    signal grp_analyze_pulse_fu_698_pulsedata_V_3_write : STD_LOGIC;
    signal grp_update_triggers_fu_783_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_update_triggers_fu_783_ap_return_8 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_update_triggers_fu_783_ap_return_9 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_update_triggers_fu_783_ap_return_10 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_update_triggers_fu_783_ap_return_11 : STD_LOGIC_VECTOR (0 downto 0);
    signal do_init_reg_454 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal icmp_ln233_fu_1121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal holdoff_V4_phi_reg_545 : STD_LOGIC_VECTOR (9 downto 0);
    signal holdoff_V4_rewind_reg_470 : STD_LOGIC_VECTOR (9 downto 0);
    signal baseline_shrink_V5_p_reg_557 : STD_LOGIC_VECTOR (8 downto 0);
    signal baseline_shrink_V5_r_reg_485 : STD_LOGIC_VECTOR (8 downto 0);
    signal baseline_grow_V6_phi_reg_569 : STD_LOGIC_VECTOR (8 downto 0);
    signal baseline_grow_V6_rew_reg_500 : STD_LOGIC_VECTOR (8 downto 0);
    signal lane_V7_phi_reg_581 : STD_LOGIC_VECTOR (1 downto 0);
    signal lane_V7_rewind_reg_515 : STD_LOGIC_VECTOR (1 downto 0);
    signal val_assign3_reg_530 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_0_reg_593 : STD_LOGIC_VECTOR (124 downto 0);
    signal empty_n_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_update_baselines_fu_620_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal select_ln239_fu_815_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln239_1_fu_823_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_analyze_pulse_fu_698_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_NS_fsm_state13 : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal pulsedata_V_0_full_n : STD_LOGIC;
    signal pulsedata_V_0_write : STD_LOGIC;
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal pulsedata_V_1_full_n : STD_LOGIC;
    signal pulsedata_V_1_write : STD_LOGIC;
    signal pulsedata_V_2_full_n : STD_LOGIC;
    signal pulsedata_V_2_write : STD_LOGIC;
    signal pulsedata_V_3_full_n : STD_LOGIC;
    signal pulsedata_V_3_write : STD_LOGIC;
    signal zext_ln237_fu_883_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln700_fu_1110_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_076_03061_fu_312 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_0218_03052_fu_316 : STD_LOGIC_VECTOR (8 downto 0);
    signal pulsedata_V_2_read_nbread_fu_358_p2_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal pulsedata_V_2_dout : STD_LOGIC_VECTOR (124 downto 0);
    signal pulsedata_V_2_empty_n : STD_LOGIC;
    signal pulsedata_V_2_read : STD_LOGIC;
    signal pulsedata_V_1_read_nbread_fu_364_p2_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal pulsedata_V_1_dout : STD_LOGIC_VECTOR (124 downto 0);
    signal pulsedata_V_1_empty_n : STD_LOGIC;
    signal pulsedata_V_1_read : STD_LOGIC;
    signal pulsedata_V_0_read_nbread_fu_370_p2_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal pulsedata_V_0_dout : STD_LOGIC_VECTOR (124 downto 0);
    signal pulsedata_V_0_empty_n : STD_LOGIC;
    signal pulsedata_V_0_read : STD_LOGIC;
    signal pulsedata_V_3_read_nbread_fu_376_p2_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal pulsedata_V_3_dout : STD_LOGIC_VECTOR (124 downto 0);
    signal pulsedata_V_3_empty_n : STD_LOGIC;
    signal pulsedata_V_3_read : STD_LOGIC;
    signal tmp_peak_time_V_load_fu_1039_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_start_V_load_new_fu_1029_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln209_fu_1069_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln214_fu_1079_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal xor_ln262_fu_1095_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln262_fu_1095_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln262_fu_1101_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal regslice_both_streamin_data_V_U_apdone_blk : STD_LOGIC;
    signal streamin_TDATA_int : STD_LOGIC_VECTOR (63 downto 0);
    signal streamin_TVALID_int : STD_LOGIC;
    signal streamin_TREADY_int : STD_LOGIC;
    signal regslice_both_streamin_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_w1_streamin_last_U_apdone_blk : STD_LOGIC;
    signal streamin_TLAST_int : STD_LOGIC;
    signal regslice_both_w1_streamin_last_U_vld_out : STD_LOGIC;
    signal regslice_both_w1_streamin_last_U_ack_in : STD_LOGIC;

    component update_baselines IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        group_V : IN STD_LOGIC_VECTOR (8 downto 0);
        phases_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        phases_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        phases_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        phases_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        grow_n_V : IN STD_LOGIC_VECTOR (8 downto 0);
        shrink_n_V : IN STD_LOGIC_VECTOR (8 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component analyze_pulse IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        group_V : IN STD_LOGIC_VECTOR (8 downto 0);
        trigdata_0_phase_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_1_phase_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_2_phase_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_3_phase_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_0_baseline : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_1_baseline : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_2_baseline : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_3_baseline : IN STD_LOGIC_VECTOR (15 downto 0);
        trigdata_0_trigger_s : IN STD_LOGIC;
        trigdata_1_trigger_s : IN STD_LOGIC;
        trigdata_2_trigger_s : IN STD_LOGIC;
        trigdata_3_trigger_s : IN STD_LOGIC;
        holdoff_V : IN STD_LOGIC_VECTOR (9 downto 0);
        timestamp_V : IN STD_LOGIC_VECTOR (63 downto 0);
        pulsedata_V_0_din : OUT STD_LOGIC_VECTOR (124 downto 0);
        pulsedata_V_0_full_n : IN STD_LOGIC;
        pulsedata_V_0_write : OUT STD_LOGIC;
        pulsedata_V_1_din : OUT STD_LOGIC_VECTOR (124 downto 0);
        pulsedata_V_1_full_n : IN STD_LOGIC;
        pulsedata_V_1_write : OUT STD_LOGIC;
        pulsedata_V_2_din : OUT STD_LOGIC_VECTOR (124 downto 0);
        pulsedata_V_2_full_n : IN STD_LOGIC;
        pulsedata_V_2_write : OUT STD_LOGIC;
        pulsedata_V_3_din : OUT STD_LOGIC_VECTOR (124 downto 0);
        pulsedata_V_3_full_n : IN STD_LOGIC;
        pulsedata_V_3_write : OUT STD_LOGIC );
    end component;


    component update_triggers IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_0_phase_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_phase_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_phase_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_phase_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_0_baseline_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_baseline_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_baseline_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_baseline_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
        trig_cfg_0_threshol : IN STD_LOGIC_VECTOR (15 downto 0);
        trig_cfg_1_threshol : IN STD_LOGIC_VECTOR (15 downto 0);
        trig_cfg_2_threshol : IN STD_LOGIC_VECTOR (15 downto 0);
        trig_cfg_3_threshol : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fifo_w125_d64_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (124 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (124 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component photon_trigger_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        triggercfg_0_threshold_V_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        triggercfg_0_threshold_V_ce0 : IN STD_LOGIC;
        triggercfg_0_threshold_V_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        triggercfg_1_threshold_V_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        triggercfg_1_threshold_V_ce0 : IN STD_LOGIC;
        triggercfg_1_threshold_V_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        triggercfg_2_threshold_V_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        triggercfg_2_threshold_V_ce0 : IN STD_LOGIC;
        triggercfg_2_threshold_V_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        triggercfg_3_threshold_V_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        triggercfg_3_threshold_V_ce0 : IN STD_LOGIC;
        triggercfg_3_threshold_V_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        holdoff_V : OUT STD_LOGIC_VECTOR (9 downto 0);
        baseline_shrink_V : OUT STD_LOGIC_VECTOR (8 downto 0);
        baseline_grow_V : OUT STD_LOGIC_VECTOR (8 downto 0);
        dropped_o : IN STD_LOGIC_VECTOR (31 downto 0);
        dropped_o_ap_vld : IN STD_LOGIC;
        dropped_i : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;


    component regslice_both_w1 IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC;
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC;
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    photon_trigger_control_s_axi_U : component photon_trigger_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        triggercfg_0_threshold_V_address0 => triggercfg_0_threshold_V_address0,
        triggercfg_0_threshold_V_ce0 => triggercfg_0_threshold_V_ce0,
        triggercfg_0_threshold_V_q0 => triggercfg_0_threshold_V_q0,
        triggercfg_1_threshold_V_address0 => triggercfg_1_threshold_V_address0,
        triggercfg_1_threshold_V_ce0 => triggercfg_1_threshold_V_ce0,
        triggercfg_1_threshold_V_q0 => triggercfg_1_threshold_V_q0,
        triggercfg_2_threshold_V_address0 => triggercfg_2_threshold_V_address0,
        triggercfg_2_threshold_V_ce0 => triggercfg_2_threshold_V_ce0,
        triggercfg_2_threshold_V_q0 => triggercfg_2_threshold_V_q0,
        triggercfg_3_threshold_V_address0 => triggercfg_3_threshold_V_address0,
        triggercfg_3_threshold_V_ce0 => triggercfg_3_threshold_V_ce0,
        triggercfg_3_threshold_V_q0 => triggercfg_3_threshold_V_q0,
        holdoff_V => holdoff_V,
        baseline_shrink_V => baseline_shrink_V,
        baseline_grow_V => baseline_grow_V,
        dropped_o => add_ln262_reg_1308,
        dropped_o_ap_vld => dropped_o_ap_vld,
        dropped_i => dropped_i);

    grp_update_baselines_fu_620 : component update_baselines
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_update_baselines_fu_620_ap_start,
        ap_done => grp_update_baselines_fu_620_ap_done,
        ap_idle => grp_update_baselines_fu_620_ap_idle,
        ap_ready => grp_update_baselines_fu_620_ap_ready,
        group_V => val_assign3_reg_530,
        phases_0_V_read => grp_update_baselines_fu_620_phases_0_V_read,
        phases_1_V_read => grp_update_baselines_fu_620_phases_1_V_read,
        phases_2_V_read => grp_update_baselines_fu_620_phases_2_V_read,
        phases_3_V_read => grp_update_baselines_fu_620_phases_3_V_read,
        grow_n_V => grp_update_baselines_fu_620_grow_n_V,
        shrink_n_V => grp_update_baselines_fu_620_shrink_n_V,
        ap_return_0 => grp_update_baselines_fu_620_ap_return_0,
        ap_return_1 => grp_update_baselines_fu_620_ap_return_1,
        ap_return_2 => grp_update_baselines_fu_620_ap_return_2,
        ap_return_3 => grp_update_baselines_fu_620_ap_return_3,
        ap_return_4 => grp_update_baselines_fu_620_ap_return_4,
        ap_return_5 => grp_update_baselines_fu_620_ap_return_5,
        ap_return_6 => grp_update_baselines_fu_620_ap_return_6,
        ap_return_7 => grp_update_baselines_fu_620_ap_return_7);

    grp_analyze_pulse_fu_698 : component analyze_pulse
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_analyze_pulse_fu_698_ap_start,
        ap_done => grp_analyze_pulse_fu_698_ap_done,
        ap_idle => grp_analyze_pulse_fu_698_ap_idle,
        ap_ready => grp_analyze_pulse_fu_698_ap_ready,
        group_V => val_assign3_reg_530,
        trigdata_0_phase_V_s => grp_update_triggers_fu_783_ap_return_0,
        trigdata_1_phase_V_s => grp_update_triggers_fu_783_ap_return_1,
        trigdata_2_phase_V_s => grp_update_triggers_fu_783_ap_return_2,
        trigdata_3_phase_V_s => grp_update_triggers_fu_783_ap_return_3,
        trigdata_0_baseline => grp_update_triggers_fu_783_ap_return_4,
        trigdata_1_baseline => grp_update_triggers_fu_783_ap_return_5,
        trigdata_2_baseline => grp_update_triggers_fu_783_ap_return_6,
        trigdata_3_baseline => grp_update_triggers_fu_783_ap_return_7,
        trigdata_0_trigger_s => grp_analyze_pulse_fu_698_trigdata_0_trigger_s,
        trigdata_1_trigger_s => grp_analyze_pulse_fu_698_trigdata_1_trigger_s,
        trigdata_2_trigger_s => grp_analyze_pulse_fu_698_trigdata_2_trigger_s,
        trigdata_3_trigger_s => grp_analyze_pulse_fu_698_trigdata_3_trigger_s,
        holdoff_V => holdoff_V4_phi_reg_545,
        timestamp_V => time_V_reg_1167,
        pulsedata_V_0_din => grp_analyze_pulse_fu_698_pulsedata_V_0_din,
        pulsedata_V_0_full_n => pulsedata_V_0_full_n,
        pulsedata_V_0_write => grp_analyze_pulse_fu_698_pulsedata_V_0_write,
        pulsedata_V_1_din => grp_analyze_pulse_fu_698_pulsedata_V_1_din,
        pulsedata_V_1_full_n => pulsedata_V_1_full_n,
        pulsedata_V_1_write => grp_analyze_pulse_fu_698_pulsedata_V_1_write,
        pulsedata_V_2_din => grp_analyze_pulse_fu_698_pulsedata_V_2_din,
        pulsedata_V_2_full_n => pulsedata_V_2_full_n,
        pulsedata_V_2_write => grp_analyze_pulse_fu_698_pulsedata_V_2_write,
        pulsedata_V_3_din => grp_analyze_pulse_fu_698_pulsedata_V_3_din,
        pulsedata_V_3_full_n => pulsedata_V_3_full_n,
        pulsedata_V_3_write => grp_analyze_pulse_fu_698_pulsedata_V_3_write);

    grp_update_triggers_fu_783 : component update_triggers
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_0_phase_V_read => basedata_0_phase_V_reg_1192,
        data_1_phase_V_read => basedata_1_phase_V_reg_1197,
        data_2_phase_V_read => basedata_2_phase_V_reg_1202,
        data_3_phase_V_read => basedata_3_phase_V_reg_1207,
        data_0_baseline_V_r => basedata_0_baseline_reg_1212,
        data_1_baseline_V_r => basedata_1_baseline_reg_1217,
        data_2_baseline_V_r => basedata_2_baseline_reg_1222,
        data_3_baseline_V_r => basedata_3_baseline_reg_1227,
        trig_cfg_0_threshol => triggercfg_0_threshold_V_q0,
        trig_cfg_1_threshol => triggercfg_1_threshold_V_q0,
        trig_cfg_2_threshol => triggercfg_2_threshold_V_q0,
        trig_cfg_3_threshol => triggercfg_3_threshold_V_q0,
        ap_return_0 => grp_update_triggers_fu_783_ap_return_0,
        ap_return_1 => grp_update_triggers_fu_783_ap_return_1,
        ap_return_2 => grp_update_triggers_fu_783_ap_return_2,
        ap_return_3 => grp_update_triggers_fu_783_ap_return_3,
        ap_return_4 => grp_update_triggers_fu_783_ap_return_4,
        ap_return_5 => grp_update_triggers_fu_783_ap_return_5,
        ap_return_6 => grp_update_triggers_fu_783_ap_return_6,
        ap_return_7 => grp_update_triggers_fu_783_ap_return_7,
        ap_return_8 => grp_update_triggers_fu_783_ap_return_8,
        ap_return_9 => grp_update_triggers_fu_783_ap_return_9,
        ap_return_10 => grp_update_triggers_fu_783_ap_return_10,
        ap_return_11 => grp_update_triggers_fu_783_ap_return_11);

    pulsedata_V_0_fifo_U : component fifo_w125_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_analyze_pulse_fu_698_pulsedata_V_0_din,
        if_full_n => pulsedata_V_0_full_n,
        if_write => pulsedata_V_0_write,
        if_dout => pulsedata_V_0_dout,
        if_empty_n => pulsedata_V_0_empty_n,
        if_read => pulsedata_V_0_read);

    pulsedata_V_1_fifo_U : component fifo_w125_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_analyze_pulse_fu_698_pulsedata_V_1_din,
        if_full_n => pulsedata_V_1_full_n,
        if_write => pulsedata_V_1_write,
        if_dout => pulsedata_V_1_dout,
        if_empty_n => pulsedata_V_1_empty_n,
        if_read => pulsedata_V_1_read);

    pulsedata_V_2_fifo_U : component fifo_w125_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_analyze_pulse_fu_698_pulsedata_V_2_din,
        if_full_n => pulsedata_V_2_full_n,
        if_write => pulsedata_V_2_write,
        if_dout => pulsedata_V_2_dout,
        if_empty_n => pulsedata_V_2_empty_n,
        if_read => pulsedata_V_2_read);

    pulsedata_V_3_fifo_U : component fifo_w125_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_analyze_pulse_fu_698_pulsedata_V_3_din,
        if_full_n => pulsedata_V_3_full_n,
        if_write => pulsedata_V_3_write,
        if_dout => pulsedata_V_3_dout,
        if_empty_n => pulsedata_V_3_empty_n,
        if_read => pulsedata_V_3_read);

    regslice_both_streamin_data_V_U : component regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => streamin_TDATA,
        vld_in => streamin_TVALID,
        ack_in => regslice_both_streamin_data_V_U_ack_in,
        data_out => streamin_TDATA_int,
        vld_out => streamin_TVALID_int,
        ack_out => streamin_TREADY_int,
        apdone_blk => regslice_both_streamin_data_V_U_apdone_blk);

    regslice_both_w1_streamin_last_U : component regslice_both_w1
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => streamin_TLAST,
        vld_in => streamin_TVALID,
        ack_in => regslice_both_w1_streamin_last_U_ack_in,
        data_out => streamin_TLAST_int,
        vld_out => regslice_both_w1_streamin_last_U_vld_out,
        ack_out => streamin_TREADY_int,
        apdone_blk => regslice_both_w1_streamin_last_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_analyze_pulse_fu_698_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_analyze_pulse_fu_698_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state13) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                    grp_analyze_pulse_fu_698_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_analyze_pulse_fu_698_ap_ready = ap_const_logic_1)) then 
                    grp_analyze_pulse_fu_698_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_update_baselines_fu_620_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_update_baselines_fu_620_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_update_baselines_fu_620_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_update_baselines_fu_620_ap_ready = ap_const_logic_1)) then 
                    grp_update_baselines_fu_620_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    baseline_grow_V6_phi_reg_569_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_0)) then 
                    baseline_grow_V6_phi_reg_569 <= baseline_grow_V6_rew_reg_500;
                elsif ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_1)) then 
                    baseline_grow_V6_phi_reg_569 <= baseline_grow_V;
                end if;
            end if; 
        end if;
    end process;

    baseline_shrink_V5_p_reg_557_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_0)) then 
                    baseline_shrink_V5_p_reg_557 <= baseline_shrink_V5_r_reg_485;
                elsif ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_1)) then 
                    baseline_shrink_V5_p_reg_557 <= baseline_shrink_V;
                end if;
            end if; 
        end if;
    end process;

    do_init_reg_454_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln233_fu_1121_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21))) then 
                do_init_reg_454 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or ((ap_const_logic_1 = ap_CS_fsm_state21) and (icmp_ln233_fu_1121_p2 = ap_const_lv1_1)))) then 
                do_init_reg_454 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    empty_n_reg_606_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                if ((t_V_reg_1232 = ap_const_lv2_0)) then 
                    empty_n_reg_606 <= pulsedata_V_0_read_nbread_fu_370_p2_0;
                elsif ((t_V_reg_1232 = ap_const_lv2_1)) then 
                    empty_n_reg_606 <= pulsedata_V_1_read_nbread_fu_364_p2_0;
                elsif ((t_V_reg_1232 = ap_const_lv2_2)) then 
                    empty_n_reg_606 <= pulsedata_V_2_read_nbread_fu_358_p2_0;
                elsif ((t_V_reg_1232 = ap_const_lv2_3)) then 
                    empty_n_reg_606 <= pulsedata_V_3_read_nbread_fu_376_p2_0;
                end if;
            end if; 
        end if;
    end process;

    holdoff_V4_phi_reg_545_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_0)) then 
                    holdoff_V4_phi_reg_545 <= holdoff_V4_rewind_reg_470;
                elsif ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_1)) then 
                    holdoff_V4_phi_reg_545 <= holdoff_V;
                end if;
            end if; 
        end if;
    end process;

    lane_V7_phi_reg_581_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_0)) then 
                    lane_V7_phi_reg_581 <= lane_V7_rewind_reg_515;
                elsif ((ap_phi_mux_do_init_phi_fu_459_p6 = ap_const_lv1_1)) then 
                    lane_V7_phi_reg_581 <= lane_V;
                end if;
            end if; 
        end if;
    end process;

    tmp_0_reg_593_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                if ((t_V_reg_1232 = ap_const_lv2_0)) then 
                    tmp_0_reg_593 <= pulsedata_V_0_dout;
                elsif ((t_V_reg_1232 = ap_const_lv2_1)) then 
                    tmp_0_reg_593 <= pulsedata_V_1_dout;
                elsif ((t_V_reg_1232 = ap_const_lv2_2)) then 
                    tmp_0_reg_593 <= pulsedata_V_2_dout;
                elsif ((t_V_reg_1232 = ap_const_lv2_3)) then 
                    tmp_0_reg_593 <= pulsedata_V_3_dout;
                end if;
            end if; 
        end if;
    end process;

    val_assign3_reg_530_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln233_fu_1121_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21))) then 
                val_assign3_reg_530 <= group_reg_1238;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or ((ap_const_logic_1 = ap_CS_fsm_state21) and (icmp_ln233_fu_1121_p2 = ap_const_lv1_1)))) then 
                val_assign3_reg_530 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                add_ln262_reg_1308 <= add_ln262_fu_1105_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                basedata_0_baseline_reg_1212 <= grp_update_baselines_fu_620_ap_return_4;
                basedata_0_phase_V_reg_1192 <= grp_update_baselines_fu_620_ap_return_0;
                basedata_1_baseline_reg_1217 <= grp_update_baselines_fu_620_ap_return_5;
                basedata_1_phase_V_reg_1197 <= grp_update_baselines_fu_620_ap_return_1;
                basedata_2_baseline_reg_1222 <= grp_update_baselines_fu_620_ap_return_6;
                basedata_2_phase_V_reg_1202 <= grp_update_baselines_fu_620_ap_return_2;
                basedata_3_baseline_reg_1227 <= grp_update_baselines_fu_620_ap_return_7;
                basedata_3_phase_V_reg_1207 <= grp_update_baselines_fu_620_ap_return_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln233_fu_1121_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state21))) then
                baseline_grow_V6_rew_reg_500 <= baseline_grow_V6_phi_reg_569;
                baseline_shrink_V5_r_reg_485 <= baseline_shrink_V5_p_reg_557;
                holdoff_V4_rewind_reg_470 <= holdoff_V4_phi_reg_545;
                lane_V7_rewind_reg_515 <= lane_V7_phi_reg_581;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state19) and (ap_phi_mux_empty_n_phi_fu_609_p8 = ap_const_lv1_1))) then
                dropped_read_reg_1303 <= dropped_i;
                event_time_V_reg_1298 <= event_time_V_fu_1073_p2;
                tmp_3_reg_1293 <= tmp_0_reg_593(24 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                event_baseline_V_reg_1288 <= tmp_0_reg_593(124 downto 109);
                event_phase_V_reg_1283 <= event_phase_V_fu_1025_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                group_reg_1238 <= group_fu_987_p2;
                t_V_reg_1232 <= next_out_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln239_reg_1161 <= icmp_ln239_fu_803_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                next_out_V <= add_ln700_fu_1110_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((timestamp_V_ap_vld = ap_const_logic_0) or (streamin_TVALID_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0218_03052_fu_316 <= select_ln239_1_fu_823_p3;
                p_076_03061_fu_312 <= select_ln239_fu_815_p3;
                time_V_reg_1167 <= timestamp_V;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (timestamp_V_ap_vld, ap_CS_fsm, ap_CS_fsm_state3, ap_CS_fsm_state19, ap_phi_mux_empty_n_phi_fu_609_p8, ap_CS_fsm_state21, icmp_ln233_fu_1121_p2, streamin_TVALID_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if ((not(((timestamp_V_ap_vld = ap_const_logic_0) or (streamin_TVALID_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                if (((ap_phi_mux_empty_n_phi_fu_609_p8 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state21) and (icmp_ln233_fu_1121_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln262_fu_1105_p2 <= std_logic_vector(unsigned(dropped_read_reg_1303) + unsigned(zext_ln262_fu_1101_p1));
    add_ln700_fu_1110_p2 <= std_logic_vector(unsigned(t_V_reg_1232) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_NS_fsm_state13 <= ap_NS_fsm(12);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);

    ap_block_state3_assign_proc : process(timestamp_V_ap_vld, streamin_TVALID_int)
    begin
                ap_block_state3 <= ((timestamp_V_ap_vld = ap_const_logic_0) or (streamin_TVALID_int = ap_const_logic_0));
    end process;

    ap_phi_mux_do_init_phi_fu_459_p6 <= do_init_reg_454;
    ap_phi_mux_empty_n_phi_fu_609_p8 <= empty_n_reg_606;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    dropped_o_ap_vld_assign_proc : process(ap_CS_fsm_state21, empty_n_reg_606)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) and (empty_n_reg_606 = ap_const_lv1_1))) then 
            dropped_o_ap_vld <= ap_const_logic_1;
        else 
            dropped_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    event_phase_V_fu_1025_p1 <= tmp_0_reg_593(16 - 1 downto 0);
    event_time_V_fu_1073_p2 <= std_logic_vector(unsigned(tmp_start_V_load_new_fu_1029_p4) + unsigned(zext_ln209_fu_1069_p1));
    events_out_V_din <= (((((event_baseline_V_reg_1288 & zext_ln214_fu_1079_p1) & tmp_3_reg_1293) & t_V_reg_1232) & event_phase_V_reg_1283) & event_time_V_reg_1298);

    events_out_V_write_assign_proc : process(events_out_V_full_n, ap_CS_fsm_state20)
    begin
        if (((events_out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            events_out_V_write <= ap_const_logic_1;
        else 
            events_out_V_write <= ap_const_logic_0;
        end if; 
    end process;

    group_fu_987_p2 <= std_logic_vector(unsigned(ap_const_lv9_1) + unsigned(val_assign3_reg_530));
    grp_analyze_pulse_fu_698_ap_start <= grp_analyze_pulse_fu_698_ap_start_reg;
    grp_analyze_pulse_fu_698_trigdata_0_trigger_s <= grp_update_triggers_fu_783_ap_return_8(0);
    grp_analyze_pulse_fu_698_trigdata_1_trigger_s <= grp_update_triggers_fu_783_ap_return_9(0);
    grp_analyze_pulse_fu_698_trigdata_2_trigger_s <= grp_update_triggers_fu_783_ap_return_10(0);
    grp_analyze_pulse_fu_698_trigdata_3_trigger_s <= grp_update_triggers_fu_783_ap_return_11(0);
    grp_update_baselines_fu_620_ap_start <= grp_update_baselines_fu_620_ap_start_reg;
    grp_update_baselines_fu_620_grow_n_V <= 
        baseline_grow_V6_phi_reg_569 when (icmp_ln239_reg_1161(0) = '1') else 
        p_076_03061_fu_312;
    grp_update_baselines_fu_620_phases_0_V_read <= streamin_TDATA_int(16 - 1 downto 0);
    grp_update_baselines_fu_620_phases_1_V_read <= streamin_TDATA_int(31 downto 16);
    grp_update_baselines_fu_620_phases_2_V_read <= streamin_TDATA_int(47 downto 32);
    grp_update_baselines_fu_620_phases_3_V_read <= streamin_TDATA_int(63 downto 48);
    grp_update_baselines_fu_620_shrink_n_V <= 
        baseline_shrink_V5_p_reg_557 when (icmp_ln239_reg_1161(0) = '1') else 
        p_0218_03052_fu_316;
    icmp_ln233_fu_1121_p2 <= "1" when (val_assign3_reg_530 = ap_const_lv9_1FF) else "0";
    icmp_ln239_fu_803_p2 <= "1" when (val_assign3_reg_530 = ap_const_lv9_0) else "0";

    pulsedata_V_0_read_assign_proc : process(t_V_reg_1232, ap_CS_fsm_state18, pulsedata_V_0_empty_n)
    begin
        if (((t_V_reg_1232 = ap_const_lv2_0) and (pulsedata_V_0_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            pulsedata_V_0_read <= ap_const_logic_1;
        else 
            pulsedata_V_0_read <= ap_const_logic_0;
        end if; 
    end process;

    pulsedata_V_0_read_nbread_fu_370_p2_0 <= (0=>(pulsedata_V_0_empty_n), others=>'-');

    pulsedata_V_0_write_assign_proc : process(grp_analyze_pulse_fu_698_pulsedata_V_0_write, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            pulsedata_V_0_write <= grp_analyze_pulse_fu_698_pulsedata_V_0_write;
        else 
            pulsedata_V_0_write <= ap_const_logic_0;
        end if; 
    end process;


    pulsedata_V_1_read_assign_proc : process(t_V_reg_1232, ap_CS_fsm_state18, pulsedata_V_1_empty_n)
    begin
        if (((pulsedata_V_1_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18) and (t_V_reg_1232 = ap_const_lv2_1))) then 
            pulsedata_V_1_read <= ap_const_logic_1;
        else 
            pulsedata_V_1_read <= ap_const_logic_0;
        end if; 
    end process;

    pulsedata_V_1_read_nbread_fu_364_p2_0 <= (0=>(pulsedata_V_1_empty_n), others=>'-');

    pulsedata_V_1_write_assign_proc : process(grp_analyze_pulse_fu_698_pulsedata_V_1_write, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            pulsedata_V_1_write <= grp_analyze_pulse_fu_698_pulsedata_V_1_write;
        else 
            pulsedata_V_1_write <= ap_const_logic_0;
        end if; 
    end process;


    pulsedata_V_2_read_assign_proc : process(t_V_reg_1232, ap_CS_fsm_state18, pulsedata_V_2_empty_n)
    begin
        if (((pulsedata_V_2_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18) and (t_V_reg_1232 = ap_const_lv2_2))) then 
            pulsedata_V_2_read <= ap_const_logic_1;
        else 
            pulsedata_V_2_read <= ap_const_logic_0;
        end if; 
    end process;

    pulsedata_V_2_read_nbread_fu_358_p2_0 <= (0=>(pulsedata_V_2_empty_n), others=>'-');

    pulsedata_V_2_write_assign_proc : process(grp_analyze_pulse_fu_698_pulsedata_V_2_write, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            pulsedata_V_2_write <= grp_analyze_pulse_fu_698_pulsedata_V_2_write;
        else 
            pulsedata_V_2_write <= ap_const_logic_0;
        end if; 
    end process;


    pulsedata_V_3_read_assign_proc : process(t_V_reg_1232, ap_CS_fsm_state18, pulsedata_V_3_empty_n)
    begin
        if (((pulsedata_V_3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18) and (t_V_reg_1232 = ap_const_lv2_3))) then 
            pulsedata_V_3_read <= ap_const_logic_1;
        else 
            pulsedata_V_3_read <= ap_const_logic_0;
        end if; 
    end process;

    pulsedata_V_3_read_nbread_fu_376_p2_0 <= (0=>(pulsedata_V_3_empty_n), others=>'-');

    pulsedata_V_3_write_assign_proc : process(grp_analyze_pulse_fu_698_pulsedata_V_3_write, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            pulsedata_V_3_write <= grp_analyze_pulse_fu_698_pulsedata_V_3_write;
        else 
            pulsedata_V_3_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln239_1_fu_823_p3 <= 
        baseline_shrink_V5_p_reg_557 when (icmp_ln239_reg_1161(0) = '1') else 
        p_0218_03052_fu_316;
    select_ln239_fu_815_p3 <= 
        baseline_grow_V6_phi_reg_569 when (icmp_ln239_reg_1161(0) = '1') else 
        p_076_03061_fu_312;

    streamin_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state3, streamin_TVALID_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            streamin_TDATA_blk_n <= streamin_TVALID_int;
        else 
            streamin_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    streamin_TREADY_assign_proc : process(streamin_TVALID, regslice_both_streamin_data_V_U_ack_in)
    begin
        if (((streamin_TVALID = ap_const_logic_1) and (regslice_both_streamin_data_V_U_ack_in = ap_const_logic_1))) then 
            streamin_TREADY <= ap_const_logic_1;
        else 
            streamin_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    streamin_TREADY_int_assign_proc : process(timestamp_V_ap_vld, ap_CS_fsm_state3, streamin_TVALID_int)
    begin
        if ((not(((timestamp_V_ap_vld = ap_const_logic_0) or (streamin_TVALID_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            streamin_TREADY_int <= ap_const_logic_1;
        else 
            streamin_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    timestamp_V_ap_ack_assign_proc : process(timestamp_V_ap_vld, ap_CS_fsm_state3, streamin_TVALID_int)
    begin
        if ((not(((timestamp_V_ap_vld = ap_const_logic_0) or (streamin_TVALID_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            timestamp_V_ap_ack <= ap_const_logic_1;
        else 
            timestamp_V_ap_ack <= ap_const_logic_0;
        end if; 
    end process;


    timestamp_V_blk_n_assign_proc : process(timestamp_V_ap_vld, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            timestamp_V_blk_n <= timestamp_V_ap_vld;
        else 
            timestamp_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tmp_peak_time_V_load_fu_1039_p4 <= tmp_0_reg_593(98 downto 89);
    tmp_start_V_load_new_fu_1029_p4 <= tmp_0_reg_593(88 downto 25);
    triggercfg_0_threshold_V_address0 <= zext_ln237_fu_883_p1(9 - 1 downto 0);

    triggercfg_0_threshold_V_ce0_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            triggercfg_0_threshold_V_ce0 <= ap_const_logic_1;
        else 
            triggercfg_0_threshold_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    triggercfg_1_threshold_V_address0 <= zext_ln237_fu_883_p1(9 - 1 downto 0);

    triggercfg_1_threshold_V_ce0_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            triggercfg_1_threshold_V_ce0 <= ap_const_logic_1;
        else 
            triggercfg_1_threshold_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    triggercfg_2_threshold_V_address0 <= zext_ln237_fu_883_p1(9 - 1 downto 0);

    triggercfg_2_threshold_V_ce0_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            triggercfg_2_threshold_V_ce0 <= ap_const_logic_1;
        else 
            triggercfg_2_threshold_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    triggercfg_3_threshold_V_address0 <= zext_ln237_fu_883_p1(9 - 1 downto 0);

    triggercfg_3_threshold_V_ce0_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            triggercfg_3_threshold_V_ce0 <= ap_const_logic_1;
        else 
            triggercfg_3_threshold_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln262_fu_1095_p0 <= (0=>events_out_V_full_n, others=>'-');
    xor_ln262_fu_1095_p2 <= (xor_ln262_fu_1095_p0 xor ap_const_lv1_1);
    zext_ln209_fu_1069_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_peak_time_V_load_fu_1039_p4),64));
    zext_ln214_fu_1079_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lane_V7_phi_reg_581),5));
    zext_ln237_fu_883_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_assign3_reg_530),64));
    zext_ln262_fu_1101_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln262_fu_1095_p2),32));
end behav;
