// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="trigger_trigger,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=1.818000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.237000,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1387,HLS_SYN_LUT=1225,HLS_VERSION=2022_1}" *)

module trigger (
        ap_clk,
        ap_rst_n,
        phase4x_in_TDATA,
        phase4x_in_TVALID,
        phase4x_in_TREADY,
        phase4x_in_TKEEP,
        phase4x_in_TSTRB,
        phase4x_in_TUSER,
        phase4x_in_TLAST,
        iq4x_in_TDATA,
        iq4x_in_TVALID,
        iq4x_in_TREADY,
        iq4x_in_TKEEP,
        iq4x_in_TSTRB,
        iq4x_in_TUSER,
        iq4x_in_TLAST,
        postage_stream_TDATA,
        postage_stream_TVALID,
        postage_stream_TREADY,
        postage_stream_TKEEP,
        postage_stream_TSTRB,
        postage_stream_TUSER,
        postage_stream_TLAST,
        timestamp_TDATA,
        timestamp_TVALID,
        timestamp_TREADY,
        photons_lane_0_TDATA,
        photons_lane_0_TVALID,
        photons_lane_0_TREADY,
        photons_lane_1_TDATA,
        photons_lane_1_TVALID,
        photons_lane_1_TREADY,
        photons_lane_2_TDATA,
        photons_lane_2_TVALID,
        photons_lane_2_TREADY,
        photons_lane_3_TDATA,
        photons_lane_3_TVALID,
        photons_lane_3_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 13;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] phase4x_in_TDATA;
input   phase4x_in_TVALID;
output   phase4x_in_TREADY;
input  [7:0] phase4x_in_TKEEP;
input  [7:0] phase4x_in_TSTRB;
input  [8:0] phase4x_in_TUSER;
input  [0:0] phase4x_in_TLAST;
input  [127:0] iq4x_in_TDATA;
input   iq4x_in_TVALID;
output   iq4x_in_TREADY;
input  [15:0] iq4x_in_TKEEP;
input  [15:0] iq4x_in_TSTRB;
input  [8:0] iq4x_in_TUSER;
input  [0:0] iq4x_in_TLAST;
output  [191:0] postage_stream_TDATA;
output   postage_stream_TVALID;
input   postage_stream_TREADY;
output  [23:0] postage_stream_TKEEP;
output  [23:0] postage_stream_TSTRB;
output  [12:0] postage_stream_TUSER;
output  [0:0] postage_stream_TLAST;
input  [39:0] timestamp_TDATA;
input   timestamp_TVALID;
output   timestamp_TREADY;
output  [63:0] photons_lane_0_TDATA;
output   photons_lane_0_TVALID;
input   photons_lane_0_TREADY;
output  [63:0] photons_lane_1_TDATA;
output   photons_lane_1_TVALID;
input   photons_lane_1_TREADY;
output  [63:0] photons_lane_2_TDATA;
output   photons_lane_2_TVALID;
input   photons_lane_2_TREADY;
output  [63:0] photons_lane_3_TDATA;
output   photons_lane_3_TVALID;
input   photons_lane_3_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire   [8:0] threshoffs_address0;
reg    threshoffs_ce0;
wire   [63:0] threshoffs_q0;
reg    desync;
reg    desync_ap_vld;
reg   [7:0] since_cache_since_3;
reg   [7:0] since_cache_since_2;
reg   [7:0] since_cache_since_1;
reg   [7:0] since_cache_since;
wire   [8:0] since_data_address0;
reg    since_data_ce0;
reg    since_data_we0;
wire   [31:0] since_data_d0;
wire   [8:0] since_data_address1;
reg    since_data_ce1;
wire   [31:0] since_data_q1;
reg   [7:0] photon_cache_lane_time_3;
reg   [15:0] photon_cache_lane_phase_2;
reg   [7:0] photon_cache_lane_time_2;
reg   [15:0] photon_cache_lane_phase_1;
reg   [7:0] photon_cache_lane_time_1;
reg   [15:0] photon_cache_lane_phase;
reg   [7:0] photon_cache_lane_time;
reg   [15:0] photon_cache_lane_phase_3;
wire   [8:0] photon_data_address0;
reg    photon_data_ce0;
reg    photon_data_we0;
wire   [95:0] photon_data_d0;
wire   [8:0] photon_data_address1;
reg    photon_data_ce1;
wire   [95:0] photon_data_q1;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg   [0:0] or_ln97_reg_1623;
reg   [0:0] or_ln97_1_reg_1642;
reg   [0:0] or_ln97_2_reg_1661;
reg   [0:0] or_ln97_3_reg_1680;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_state5_io;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] or_ln97_reg_1623_pp0_iter4_reg;
reg   [0:0] or_ln97_1_reg_1642_pp0_iter4_reg;
reg   [0:0] or_ln97_2_reg_1661_pp0_iter4_reg;
reg   [0:0] or_ln97_3_reg_1680_pp0_iter4_reg;
wire    regslice_both_postage_stream_V_data_V_U_apdone_blk;
wire    regslice_both_photons_lane_0_U_apdone_blk;
wire    regslice_both_photons_lane_1_U_apdone_blk;
wire    regslice_both_photons_lane_2_U_apdone_blk;
wire    regslice_both_photons_lane_3_U_apdone_blk;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state6_io;
reg    ap_enable_reg_pp0_iter5;
reg    ap_block_pp0_stage0_11001;
reg    phase4x_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    iq4x_in_TDATA_blk_n;
reg    postage_stream_TDATA_blk_n;
reg    timestamp_TDATA_blk_n;
reg    photons_lane_0_TDATA_blk_n;
reg    photons_lane_1_TDATA_blk_n;
reg    photons_lane_2_TDATA_blk_n;
reg    photons_lane_3_TDATA_blk_n;
reg   [63:0] tmp_data_V_1_reg_1315;
reg   [63:0] tmp_data_V_1_reg_1315_pp0_iter1_reg;
reg   [63:0] tmp_data_V_1_reg_1315_pp0_iter2_reg;
reg   [63:0] tmp_data_V_1_reg_1315_pp0_iter3_reg;
reg   [8:0] tmp_user_V_1_reg_1324;
reg   [8:0] tmp_user_V_1_reg_1324_pp0_iter1_reg;
reg   [8:0] tmp_user_V_1_reg_1324_pp0_iter2_reg;
reg   [8:0] tmp_user_V_1_reg_1324_pp0_iter3_reg;
reg   [0:0] tmp_last_V_reg_1332;
reg   [0:0] tmp_last_V_reg_1332_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_1332_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_1332_pp0_iter3_reg;
reg   [127:0] tmp_data_V_2_reg_1337;
reg   [127:0] tmp_data_V_2_reg_1337_pp0_iter1_reg;
reg   [127:0] tmp_data_V_2_reg_1337_pp0_iter2_reg;
reg   [127:0] tmp_data_V_2_reg_1337_pp0_iter3_reg;
wire   [35:0] tmp_fu_395_p1;
reg   [35:0] tmp_reg_1342;
reg   [35:0] tmp_reg_1342_pp0_iter1_reg;
reg   [35:0] tmp_reg_1342_pp0_iter2_reg;
reg   [35:0] tmp_reg_1342_pp0_iter3_reg;
wire   [0:0] xor_ln1069_fu_399_p2;
reg   [0:0] xor_ln1069_reg_1350;
wire   [7:0] sinces_since_fu_412_p1;
reg   [7:0] sinces_since_reg_1369;
reg   [7:0] sinces_since_reg_1369_pp0_iter2_reg;
reg   [7:0] sinces_since_1_reg_1377;
reg   [7:0] sinces_since_1_reg_1377_pp0_iter2_reg;
reg   [7:0] sinces_since_2_reg_1385;
reg   [7:0] sinces_since_2_reg_1385_pp0_iter2_reg;
reg   [7:0] sinces_since_3_reg_1393;
reg   [7:0] sinces_since_3_reg_1393_pp0_iter2_reg;
wire   [7:0] photons_lane_time_fu_446_p1;
reg   [7:0] photons_lane_time_reg_1401;
reg   [7:0] photons_lane_time_reg_1401_pp0_iter2_reg;
reg   [15:0] photons_lane_phase_reg_1407;
reg   [15:0] photons_lane_phase_reg_1407_pp0_iter2_reg;
reg   [7:0] photons_lane_time_1_reg_1414;
reg   [7:0] photons_lane_time_1_reg_1414_pp0_iter2_reg;
reg   [15:0] photons_lane_phase_1_reg_1420;
reg   [15:0] photons_lane_phase_1_reg_1420_pp0_iter2_reg;
reg   [7:0] photons_lane_time_2_reg_1427;
reg   [7:0] photons_lane_time_2_reg_1427_pp0_iter2_reg;
reg   [15:0] photons_lane_phase_2_reg_1433;
reg   [15:0] photons_lane_phase_2_reg_1433_pp0_iter2_reg;
reg   [7:0] photons_lane_time_3_reg_1440;
reg   [7:0] photons_lane_time_3_reg_1440_pp0_iter2_reg;
reg   [15:0] photons_lane_phase_3_reg_1446;
reg   [15:0] photons_lane_phase_3_reg_1446_pp0_iter2_reg;
reg   [7:0] hoffs_reg_1453;
reg   [7:0] hoffs_reg_1453_pp0_iter2_reg;
reg   [7:0] hoffs_1_reg_1459;
reg   [7:0] hoffs_1_reg_1459_pp0_iter2_reg;
reg   [7:0] hoffs_2_reg_1465;
reg   [7:0] hoffs_2_reg_1465_pp0_iter2_reg;
reg   [7:0] hoffs_3_reg_1471;
reg   [7:0] hoffs_3_reg_1471_pp0_iter2_reg;
wire   [7:0] trunc_ln884_fu_560_p1;
reg   [7:0] trunc_ln884_reg_1477;
reg   [7:0] tmp_1_reg_1482;
reg   [7:0] tmp_3_reg_1487;
reg   [7:0] tmp_4_reg_1492;
wire   [8:0] last_group_fu_594_p2;
reg   [8:0] last_group_reg_1497;
wire   [15:0] phase_fu_599_p1;
reg   [15:0] phase_reg_1502;
wire   [0:0] icmp_ln1696_fu_609_p2;
reg   [0:0] icmp_ln1696_reg_1508;
wire   [0:0] icmp_ln90_fu_615_p2;
reg   [0:0] icmp_ln90_reg_1513;
wire   [0:0] update_photon_fu_620_p2;
reg   [0:0] update_photon_reg_1519;
wire   [7:0] new_since_fu_625_p2;
reg   [7:0] new_since_reg_1525;
wire   [15:0] phase_1_fu_630_p4;
reg   [15:0] phase_1_reg_1531;
wire   [0:0] icmp_ln1696_1_fu_646_p2;
reg   [0:0] icmp_ln1696_1_reg_1537;
wire   [0:0] icmp_ln90_1_fu_652_p2;
reg   [0:0] icmp_ln90_1_reg_1542;
wire   [0:0] update_photon_1_fu_657_p2;
reg   [0:0] update_photon_1_reg_1548;
wire   [7:0] new_since_1_fu_662_p2;
reg   [7:0] new_since_1_reg_1554;
wire   [15:0] phase_2_fu_667_p4;
reg   [15:0] phase_2_reg_1560;
wire   [0:0] icmp_ln1696_2_fu_683_p2;
reg   [0:0] icmp_ln1696_2_reg_1566;
wire   [0:0] icmp_ln90_2_fu_689_p2;
reg   [0:0] icmp_ln90_2_reg_1571;
wire   [0:0] update_photon_2_fu_694_p2;
reg   [0:0] update_photon_2_reg_1577;
wire   [7:0] new_since_2_fu_699_p2;
reg   [7:0] new_since_2_reg_1583;
wire   [15:0] phase_3_fu_704_p4;
reg   [15:0] phase_3_reg_1589;
wire   [0:0] icmp_ln1696_3_fu_720_p2;
reg   [0:0] icmp_ln1696_3_reg_1595;
wire   [0:0] icmp_ln90_3_fu_726_p2;
reg   [0:0] icmp_ln90_3_reg_1600;
wire   [0:0] update_photon_3_fu_731_p2;
reg   [0:0] update_photon_3_reg_1606;
wire   [7:0] new_since_3_fu_736_p2;
reg   [7:0] new_since_3_reg_1612;
wire   [0:0] trig_fu_828_p2;
reg   [0:0] trig_reg_1618;
wire   [0:0] or_ln97_fu_837_p2;
wire   [7:0] photons_lane_time_4_fu_843_p3;
reg   [7:0] photons_lane_time_4_reg_1627;
wire   [15:0] photons_lane_phase_13_fu_892_p3;
reg   [15:0] photons_lane_phase_13_reg_1632;
wire   [0:0] trig_1_fu_899_p2;
reg   [0:0] trig_1_reg_1637;
wire   [0:0] or_ln97_1_fu_908_p2;
wire   [7:0] photons_lane_time_6_fu_914_p3;
reg   [7:0] photons_lane_time_6_reg_1646;
wire   [15:0] photons_lane_phase_15_fu_963_p3;
reg   [15:0] photons_lane_phase_15_reg_1651;
wire   [0:0] trig_2_fu_970_p2;
reg   [0:0] trig_2_reg_1656;
wire   [0:0] or_ln97_2_fu_979_p2;
wire   [7:0] photons_lane_time_8_fu_985_p3;
reg   [7:0] photons_lane_time_8_reg_1665;
wire   [15:0] photons_lane_phase_17_fu_1034_p3;
reg   [15:0] photons_lane_phase_17_reg_1670;
wire   [0:0] trig_3_fu_1041_p2;
reg   [0:0] trig_3_reg_1675;
wire   [0:0] or_ln97_3_fu_1050_p2;
wire   [7:0] photons_lane_time_10_fu_1056_p3;
reg   [7:0] photons_lane_time_10_reg_1684;
wire   [15:0] photons_lane_phase_19_fu_1105_p3;
reg   [15:0] photons_lane_phase_19_reg_1689;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
wire   [63:0] zext_ln587_1_fu_405_p1;
wire   [63:0] zext_ln587_fu_741_p1;
wire   [7:0] sinces_since_5_fu_864_p3;
wire   [7:0] sinces_since_7_fu_935_p3;
wire   [7:0] sinces_since_9_fu_1006_p3;
wire   [7:0] sinces_since_11_fu_1077_p3;
wire   [7:0] photons_lane_time_5_fu_878_p3;
wire   [7:0] photons_lane_time_7_fu_949_p3;
wire   [7:0] photons_lane_time_9_fu_1020_p3;
wire   [7:0] photons_lane_time_11_fu_1091_p3;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] shl_ln_fu_602_p3;
wire   [15:0] shl_ln884_1_fu_639_p3;
wire   [15:0] shl_ln884_2_fu_676_p3;
wire   [15:0] shl_ln884_3_fu_713_p3;
wire   [0:0] icmp_ln97_fu_832_p2;
wire   [0:0] xor_ln90_fu_859_p2;
wire   [7:0] select_ln90_fu_853_p3;
wire   [7:0] select_ln90_2_fu_871_p3;
wire   [15:0] photons_lane_phase_12_fu_848_p3;
wire   [15:0] select_ln90_4_fu_885_p3;
wire   [0:0] icmp_ln97_1_fu_903_p2;
wire   [0:0] xor_ln90_1_fu_930_p2;
wire   [7:0] select_ln90_6_fu_924_p3;
wire   [7:0] select_ln90_8_fu_942_p3;
wire   [15:0] photons_lane_phase_14_fu_919_p3;
wire   [15:0] select_ln90_10_fu_956_p3;
wire   [0:0] icmp_ln97_2_fu_974_p2;
wire   [0:0] xor_ln90_2_fu_1001_p2;
wire   [7:0] select_ln90_12_fu_995_p3;
wire   [7:0] select_ln90_14_fu_1013_p3;
wire   [15:0] photons_lane_phase_16_fu_990_p3;
wire   [15:0] select_ln90_16_fu_1027_p3;
wire   [0:0] icmp_ln97_3_fu_1045_p2;
wire   [0:0] xor_ln90_3_fu_1072_p2;
wire   [7:0] select_ln90_18_fu_1066_p3;
wire   [7:0] select_ln90_20_fu_1084_p3;
wire   [15:0] photons_lane_phase_18_fu_1061_p3;
wire   [15:0] select_ln90_22_fu_1098_p3;
wire   [35:0] zext_ln232_fu_1191_p1;
wire   [35:0] photon_out_time_V_fu_1194_p2;
wire   [62:0] tmp_2_fu_1199_p5;
wire   [10:0] photon_out_id_V_fu_1184_p3;
wire   [35:0] zext_ln232_1_fu_1220_p1;
wire   [10:0] photon_out_id_V_1_fu_1214_p2;
wire   [35:0] photon_out_time_V_1_fu_1223_p2;
wire   [62:0] tmp_5_fu_1228_p4;
wire   [35:0] zext_ln232_2_fu_1248_p1;
wire   [10:0] photon_out_id_V_2_fu_1242_p2;
wire   [35:0] photon_out_time_V_2_fu_1251_p2;
wire   [62:0] tmp_8_fu_1256_p4;
wire   [35:0] zext_ln232_3_fu_1276_p1;
wire   [10:0] photon_out_id_V_3_fu_1270_p2;
wire   [35:0] photon_out_time_V_3_fu_1279_p2;
wire   [62:0] tmp_s_fu_1284_p4;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_phase4x_in_V_data_V_U_apdone_blk;
wire   [63:0] phase4x_in_TDATA_int_regslice;
wire    phase4x_in_TVALID_int_regslice;
reg    phase4x_in_TREADY_int_regslice;
wire    regslice_both_phase4x_in_V_data_V_U_ack_in;
wire    regslice_both_phase4x_in_V_keep_V_U_apdone_blk;
wire   [7:0] phase4x_in_TKEEP_int_regslice;
wire    regslice_both_phase4x_in_V_keep_V_U_vld_out;
wire    regslice_both_phase4x_in_V_keep_V_U_ack_in;
wire    regslice_both_phase4x_in_V_strb_V_U_apdone_blk;
wire   [7:0] phase4x_in_TSTRB_int_regslice;
wire    regslice_both_phase4x_in_V_strb_V_U_vld_out;
wire    regslice_both_phase4x_in_V_strb_V_U_ack_in;
wire    regslice_both_phase4x_in_V_user_V_U_apdone_blk;
wire   [8:0] phase4x_in_TUSER_int_regslice;
wire    regslice_both_phase4x_in_V_user_V_U_vld_out;
wire    regslice_both_phase4x_in_V_user_V_U_ack_in;
wire    regslice_both_phase4x_in_V_last_V_U_apdone_blk;
wire   [0:0] phase4x_in_TLAST_int_regslice;
wire    regslice_both_phase4x_in_V_last_V_U_vld_out;
wire    regslice_both_phase4x_in_V_last_V_U_ack_in;
wire    regslice_both_iq4x_in_V_data_V_U_apdone_blk;
wire   [127:0] iq4x_in_TDATA_int_regslice;
wire    iq4x_in_TVALID_int_regslice;
reg    iq4x_in_TREADY_int_regslice;
wire    regslice_both_iq4x_in_V_data_V_U_ack_in;
wire    regslice_both_iq4x_in_V_keep_V_U_apdone_blk;
wire   [15:0] iq4x_in_TKEEP_int_regslice;
wire    regslice_both_iq4x_in_V_keep_V_U_vld_out;
wire    regslice_both_iq4x_in_V_keep_V_U_ack_in;
wire    regslice_both_iq4x_in_V_strb_V_U_apdone_blk;
wire   [15:0] iq4x_in_TSTRB_int_regslice;
wire    regslice_both_iq4x_in_V_strb_V_U_vld_out;
wire    regslice_both_iq4x_in_V_strb_V_U_ack_in;
wire    regslice_both_iq4x_in_V_user_V_U_apdone_blk;
wire   [8:0] iq4x_in_TUSER_int_regslice;
wire    regslice_both_iq4x_in_V_user_V_U_vld_out;
wire    regslice_both_iq4x_in_V_user_V_U_ack_in;
wire    regslice_both_iq4x_in_V_last_V_U_apdone_blk;
wire   [0:0] iq4x_in_TLAST_int_regslice;
wire    regslice_both_iq4x_in_V_last_V_U_vld_out;
wire    regslice_both_iq4x_in_V_last_V_U_ack_in;
wire   [191:0] postage_stream_TDATA_int_regslice;
reg    postage_stream_TVALID_int_regslice;
wire    postage_stream_TREADY_int_regslice;
wire    regslice_both_postage_stream_V_data_V_U_vld_out;
wire    regslice_both_postage_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_postage_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_postage_stream_V_keep_V_U_vld_out;
wire    regslice_both_postage_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_postage_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_postage_stream_V_strb_V_U_vld_out;
wire    regslice_both_postage_stream_V_user_V_U_apdone_blk;
wire   [12:0] postage_stream_TUSER_int_regslice;
wire    regslice_both_postage_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_postage_stream_V_user_V_U_vld_out;
wire    regslice_both_postage_stream_V_last_V_U_apdone_blk;
wire    regslice_both_postage_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_postage_stream_V_last_V_U_vld_out;
wire    regslice_both_timestamp_U_apdone_blk;
wire   [39:0] timestamp_TDATA_int_regslice;
wire    timestamp_TVALID_int_regslice;
reg    timestamp_TREADY_int_regslice;
wire    regslice_both_timestamp_U_ack_in;
wire   [63:0] photons_lane_0_TDATA_int_regslice;
reg    photons_lane_0_TVALID_int_regslice;
wire    photons_lane_0_TREADY_int_regslice;
wire    regslice_both_photons_lane_0_U_vld_out;
wire   [63:0] photons_lane_1_TDATA_int_regslice;
reg    photons_lane_1_TVALID_int_regslice;
wire    photons_lane_1_TREADY_int_regslice;
wire    regslice_both_photons_lane_1_U_vld_out;
wire   [63:0] photons_lane_2_TDATA_int_regslice;
reg    photons_lane_2_TVALID_int_regslice;
wire    photons_lane_2_TREADY_int_regslice;
wire    regslice_both_photons_lane_2_U_vld_out;
wire   [63:0] photons_lane_3_TDATA_int_regslice;
reg    photons_lane_3_TVALID_int_regslice;
wire    photons_lane_3_TREADY_int_regslice;
wire    regslice_both_photons_lane_3_U_vld_out;
reg    ap_condition_519;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 since_cache_since_3 = 8'd0;
#0 since_cache_since_2 = 8'd0;
#0 since_cache_since_1 = 8'd0;
#0 since_cache_since = 8'd0;
#0 photon_cache_lane_time_3 = 8'd0;
#0 photon_cache_lane_phase_2 = 16'd0;
#0 photon_cache_lane_time_2 = 8'd0;
#0 photon_cache_lane_phase_1 = 16'd0;
#0 photon_cache_lane_time_1 = 8'd0;
#0 photon_cache_lane_phase = 16'd0;
#0 photon_cache_lane_time = 8'd0;
#0 photon_cache_lane_phase_3 = 16'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

trigger_since_data_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
since_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(since_data_address0),
    .ce0(since_data_ce0),
    .we0(since_data_we0),
    .d0(since_data_d0),
    .address1(since_data_address1),
    .ce1(since_data_ce1),
    .q1(since_data_q1)
);

trigger_photon_data_RAM_AUTO_1R1W #(
    .DataWidth( 96 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
photon_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(photon_data_address0),
    .ce0(photon_data_ce0),
    .we0(photon_data_we0),
    .d0(photon_data_d0),
    .address1(photon_data_address1),
    .ce1(photon_data_ce1),
    .q1(photon_data_q1)
);

trigger_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .desync(desync),
    .desync_ap_vld(desync_ap_vld),
    .threshoffs_address0(threshoffs_address0),
    .threshoffs_ce0(threshoffs_ce0),
    .threshoffs_q0(threshoffs_q0)
);

trigger_regslice_both #(
    .DataWidth( 64 ))
regslice_both_phase4x_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(phase4x_in_TDATA),
    .vld_in(phase4x_in_TVALID),
    .ack_in(regslice_both_phase4x_in_V_data_V_U_ack_in),
    .data_out(phase4x_in_TDATA_int_regslice),
    .vld_out(phase4x_in_TVALID_int_regslice),
    .ack_out(phase4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_phase4x_in_V_data_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 8 ))
regslice_both_phase4x_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(phase4x_in_TKEEP),
    .vld_in(phase4x_in_TVALID),
    .ack_in(regslice_both_phase4x_in_V_keep_V_U_ack_in),
    .data_out(phase4x_in_TKEEP_int_regslice),
    .vld_out(regslice_both_phase4x_in_V_keep_V_U_vld_out),
    .ack_out(phase4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_phase4x_in_V_keep_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 8 ))
regslice_both_phase4x_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(phase4x_in_TSTRB),
    .vld_in(phase4x_in_TVALID),
    .ack_in(regslice_both_phase4x_in_V_strb_V_U_ack_in),
    .data_out(phase4x_in_TSTRB_int_regslice),
    .vld_out(regslice_both_phase4x_in_V_strb_V_U_vld_out),
    .ack_out(phase4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_phase4x_in_V_strb_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 9 ))
regslice_both_phase4x_in_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(phase4x_in_TUSER),
    .vld_in(phase4x_in_TVALID),
    .ack_in(regslice_both_phase4x_in_V_user_V_U_ack_in),
    .data_out(phase4x_in_TUSER_int_regslice),
    .vld_out(regslice_both_phase4x_in_V_user_V_U_vld_out),
    .ack_out(phase4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_phase4x_in_V_user_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 1 ))
regslice_both_phase4x_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(phase4x_in_TLAST),
    .vld_in(phase4x_in_TVALID),
    .ack_in(regslice_both_phase4x_in_V_last_V_U_ack_in),
    .data_out(phase4x_in_TLAST_int_regslice),
    .vld_out(regslice_both_phase4x_in_V_last_V_U_vld_out),
    .ack_out(phase4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_phase4x_in_V_last_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 128 ))
regslice_both_iq4x_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(iq4x_in_TDATA),
    .vld_in(iq4x_in_TVALID),
    .ack_in(regslice_both_iq4x_in_V_data_V_U_ack_in),
    .data_out(iq4x_in_TDATA_int_regslice),
    .vld_out(iq4x_in_TVALID_int_regslice),
    .ack_out(iq4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_iq4x_in_V_data_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 16 ))
regslice_both_iq4x_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(iq4x_in_TKEEP),
    .vld_in(iq4x_in_TVALID),
    .ack_in(regslice_both_iq4x_in_V_keep_V_U_ack_in),
    .data_out(iq4x_in_TKEEP_int_regslice),
    .vld_out(regslice_both_iq4x_in_V_keep_V_U_vld_out),
    .ack_out(iq4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_iq4x_in_V_keep_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 16 ))
regslice_both_iq4x_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(iq4x_in_TSTRB),
    .vld_in(iq4x_in_TVALID),
    .ack_in(regslice_both_iq4x_in_V_strb_V_U_ack_in),
    .data_out(iq4x_in_TSTRB_int_regslice),
    .vld_out(regslice_both_iq4x_in_V_strb_V_U_vld_out),
    .ack_out(iq4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_iq4x_in_V_strb_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 9 ))
regslice_both_iq4x_in_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(iq4x_in_TUSER),
    .vld_in(iq4x_in_TVALID),
    .ack_in(regslice_both_iq4x_in_V_user_V_U_ack_in),
    .data_out(iq4x_in_TUSER_int_regslice),
    .vld_out(regslice_both_iq4x_in_V_user_V_U_vld_out),
    .ack_out(iq4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_iq4x_in_V_user_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 1 ))
regslice_both_iq4x_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(iq4x_in_TLAST),
    .vld_in(iq4x_in_TVALID),
    .ack_in(regslice_both_iq4x_in_V_last_V_U_ack_in),
    .data_out(iq4x_in_TLAST_int_regslice),
    .vld_out(regslice_both_iq4x_in_V_last_V_U_vld_out),
    .ack_out(iq4x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_iq4x_in_V_last_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 192 ))
regslice_both_postage_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(postage_stream_TDATA_int_regslice),
    .vld_in(postage_stream_TVALID_int_regslice),
    .ack_in(postage_stream_TREADY_int_regslice),
    .data_out(postage_stream_TDATA),
    .vld_out(regslice_both_postage_stream_V_data_V_U_vld_out),
    .ack_out(postage_stream_TREADY),
    .apdone_blk(regslice_both_postage_stream_V_data_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 24 ))
regslice_both_postage_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(24'd0),
    .vld_in(postage_stream_TVALID_int_regslice),
    .ack_in(regslice_both_postage_stream_V_keep_V_U_ack_in_dummy),
    .data_out(postage_stream_TKEEP),
    .vld_out(regslice_both_postage_stream_V_keep_V_U_vld_out),
    .ack_out(postage_stream_TREADY),
    .apdone_blk(regslice_both_postage_stream_V_keep_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 24 ))
regslice_both_postage_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(24'd0),
    .vld_in(postage_stream_TVALID_int_regslice),
    .ack_in(regslice_both_postage_stream_V_strb_V_U_ack_in_dummy),
    .data_out(postage_stream_TSTRB),
    .vld_out(regslice_both_postage_stream_V_strb_V_U_vld_out),
    .ack_out(postage_stream_TREADY),
    .apdone_blk(regslice_both_postage_stream_V_strb_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 13 ))
regslice_both_postage_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(postage_stream_TUSER_int_regslice),
    .vld_in(postage_stream_TVALID_int_regslice),
    .ack_in(regslice_both_postage_stream_V_user_V_U_ack_in_dummy),
    .data_out(postage_stream_TUSER),
    .vld_out(regslice_both_postage_stream_V_user_V_U_vld_out),
    .ack_out(postage_stream_TREADY),
    .apdone_blk(regslice_both_postage_stream_V_user_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 1 ))
regslice_both_postage_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_1332_pp0_iter3_reg),
    .vld_in(postage_stream_TVALID_int_regslice),
    .ack_in(regslice_both_postage_stream_V_last_V_U_ack_in_dummy),
    .data_out(postage_stream_TLAST),
    .vld_out(regslice_both_postage_stream_V_last_V_U_vld_out),
    .ack_out(postage_stream_TREADY),
    .apdone_blk(regslice_both_postage_stream_V_last_V_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 40 ))
regslice_both_timestamp_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(timestamp_TDATA),
    .vld_in(timestamp_TVALID),
    .ack_in(regslice_both_timestamp_U_ack_in),
    .data_out(timestamp_TDATA_int_regslice),
    .vld_out(timestamp_TVALID_int_regslice),
    .ack_out(timestamp_TREADY_int_regslice),
    .apdone_blk(regslice_both_timestamp_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 64 ))
regslice_both_photons_lane_0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(photons_lane_0_TDATA_int_regslice),
    .vld_in(photons_lane_0_TVALID_int_regslice),
    .ack_in(photons_lane_0_TREADY_int_regslice),
    .data_out(photons_lane_0_TDATA),
    .vld_out(regslice_both_photons_lane_0_U_vld_out),
    .ack_out(photons_lane_0_TREADY),
    .apdone_blk(regslice_both_photons_lane_0_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 64 ))
regslice_both_photons_lane_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(photons_lane_1_TDATA_int_regslice),
    .vld_in(photons_lane_1_TVALID_int_regslice),
    .ack_in(photons_lane_1_TREADY_int_regslice),
    .data_out(photons_lane_1_TDATA),
    .vld_out(regslice_both_photons_lane_1_U_vld_out),
    .ack_out(photons_lane_1_TREADY),
    .apdone_blk(regslice_both_photons_lane_1_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 64 ))
regslice_both_photons_lane_2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(photons_lane_2_TDATA_int_regslice),
    .vld_in(photons_lane_2_TVALID_int_regslice),
    .ack_in(photons_lane_2_TREADY_int_regslice),
    .data_out(photons_lane_2_TDATA),
    .vld_out(regslice_both_photons_lane_2_U_vld_out),
    .ack_out(photons_lane_2_TREADY),
    .apdone_blk(regslice_both_photons_lane_2_U_apdone_blk)
);

trigger_regslice_both #(
    .DataWidth( 64 ))
regslice_both_photons_lane_3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(photons_lane_3_TDATA_int_regslice),
    .vld_in(photons_lane_3_TVALID_int_regslice),
    .ack_in(photons_lane_3_TREADY_int_regslice),
    .data_out(photons_lane_3_TDATA),
    .vld_out(regslice_both_photons_lane_3_U_vld_out),
    .ack_out(photons_lane_3_TREADY),
    .apdone_blk(regslice_both_photons_lane_3_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        hoffs_1_reg_1459 <= {{threshoffs_q0[31:24]}};
        hoffs_2_reg_1465 <= {{threshoffs_q0[47:40]}};
        hoffs_3_reg_1471 <= {{threshoffs_q0[63:56]}};
        hoffs_reg_1453 <= {{threshoffs_q0[15:8]}};
        photons_lane_phase_1_reg_1420 <= {{photon_data_q1[47:32]}};
        photons_lane_phase_2_reg_1433 <= {{photon_data_q1[71:56]}};
        photons_lane_phase_3_reg_1446 <= {{photon_data_q1[95:80]}};
        photons_lane_phase_reg_1407 <= {{photon_data_q1[23:8]}};
        photons_lane_time_1_reg_1414 <= {{photon_data_q1[31:24]}};
        photons_lane_time_2_reg_1427 <= {{photon_data_q1[55:48]}};
        photons_lane_time_3_reg_1440 <= {{photon_data_q1[79:72]}};
        photons_lane_time_reg_1401 <= photons_lane_time_fu_446_p1;
        sinces_since_1_reg_1377 <= {{since_data_q1[15:8]}};
        sinces_since_2_reg_1385 <= {{since_data_q1[23:16]}};
        sinces_since_3_reg_1393 <= {{since_data_q1[31:24]}};
        sinces_since_reg_1369 <= sinces_since_fu_412_p1;
        tmp_1_reg_1482 <= {{threshoffs_q0[23:16]}};
        tmp_3_reg_1487 <= {{threshoffs_q0[39:32]}};
        tmp_4_reg_1492 <= {{threshoffs_q0[55:48]}};
        tmp_data_V_1_reg_1315 <= phase4x_in_TDATA_int_regslice;
        tmp_data_V_1_reg_1315_pp0_iter1_reg <= tmp_data_V_1_reg_1315;
        tmp_data_V_2_reg_1337 <= iq4x_in_TDATA_int_regslice;
        tmp_data_V_2_reg_1337_pp0_iter1_reg <= tmp_data_V_2_reg_1337;
        tmp_last_V_reg_1332 <= phase4x_in_TLAST_int_regslice;
        tmp_last_V_reg_1332_pp0_iter1_reg <= tmp_last_V_reg_1332;
        tmp_reg_1342 <= tmp_fu_395_p1;
        tmp_reg_1342_pp0_iter1_reg <= tmp_reg_1342;
        tmp_user_V_1_reg_1324 <= phase4x_in_TUSER_int_regslice;
        tmp_user_V_1_reg_1324_pp0_iter1_reg <= tmp_user_V_1_reg_1324;
        trunc_ln884_reg_1477 <= trunc_ln884_fu_560_p1;
        xor_ln1069_reg_1350 <= xor_ln1069_fu_399_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        hoffs_1_reg_1459_pp0_iter2_reg <= hoffs_1_reg_1459;
        hoffs_2_reg_1465_pp0_iter2_reg <= hoffs_2_reg_1465;
        hoffs_3_reg_1471_pp0_iter2_reg <= hoffs_3_reg_1471;
        hoffs_reg_1453_pp0_iter2_reg <= hoffs_reg_1453;
        icmp_ln1696_1_reg_1537 <= icmp_ln1696_1_fu_646_p2;
        icmp_ln1696_2_reg_1566 <= icmp_ln1696_2_fu_683_p2;
        icmp_ln1696_3_reg_1595 <= icmp_ln1696_3_fu_720_p2;
        icmp_ln1696_reg_1508 <= icmp_ln1696_fu_609_p2;
        icmp_ln90_1_reg_1542 <= icmp_ln90_1_fu_652_p2;
        icmp_ln90_2_reg_1571 <= icmp_ln90_2_fu_689_p2;
        icmp_ln90_3_reg_1600 <= icmp_ln90_3_fu_726_p2;
        icmp_ln90_reg_1513 <= icmp_ln90_fu_615_p2;
        last_group_reg_1497 <= last_group_fu_594_p2;
        new_since_1_reg_1554 <= new_since_1_fu_662_p2;
        new_since_2_reg_1583 <= new_since_2_fu_699_p2;
        new_since_3_reg_1612 <= new_since_3_fu_736_p2;
        new_since_reg_1525 <= new_since_fu_625_p2;
        or_ln97_1_reg_1642 <= or_ln97_1_fu_908_p2;
        or_ln97_1_reg_1642_pp0_iter4_reg <= or_ln97_1_reg_1642;
        or_ln97_2_reg_1661 <= or_ln97_2_fu_979_p2;
        or_ln97_2_reg_1661_pp0_iter4_reg <= or_ln97_2_reg_1661;
        or_ln97_3_reg_1680 <= or_ln97_3_fu_1050_p2;
        or_ln97_3_reg_1680_pp0_iter4_reg <= or_ln97_3_reg_1680;
        or_ln97_reg_1623 <= or_ln97_fu_837_p2;
        or_ln97_reg_1623_pp0_iter4_reg <= or_ln97_reg_1623;
        phase_1_reg_1531 <= {{tmp_data_V_1_reg_1315_pp0_iter1_reg[31:16]}};
        phase_2_reg_1560 <= {{tmp_data_V_1_reg_1315_pp0_iter1_reg[47:32]}};
        phase_3_reg_1589 <= {{tmp_data_V_1_reg_1315_pp0_iter1_reg[63:48]}};
        phase_reg_1502 <= phase_fu_599_p1;
        photons_lane_phase_13_reg_1632 <= photons_lane_phase_13_fu_892_p3;
        photons_lane_phase_15_reg_1651 <= photons_lane_phase_15_fu_963_p3;
        photons_lane_phase_17_reg_1670 <= photons_lane_phase_17_fu_1034_p3;
        photons_lane_phase_19_reg_1689 <= photons_lane_phase_19_fu_1105_p3;
        photons_lane_phase_1_reg_1420_pp0_iter2_reg <= photons_lane_phase_1_reg_1420;
        photons_lane_phase_2_reg_1433_pp0_iter2_reg <= photons_lane_phase_2_reg_1433;
        photons_lane_phase_3_reg_1446_pp0_iter2_reg <= photons_lane_phase_3_reg_1446;
        photons_lane_phase_reg_1407_pp0_iter2_reg <= photons_lane_phase_reg_1407;
        photons_lane_time_10_reg_1684 <= photons_lane_time_10_fu_1056_p3;
        photons_lane_time_1_reg_1414_pp0_iter2_reg <= photons_lane_time_1_reg_1414;
        photons_lane_time_2_reg_1427_pp0_iter2_reg <= photons_lane_time_2_reg_1427;
        photons_lane_time_3_reg_1440_pp0_iter2_reg <= photons_lane_time_3_reg_1440;
        photons_lane_time_4_reg_1627 <= photons_lane_time_4_fu_843_p3;
        photons_lane_time_6_reg_1646 <= photons_lane_time_6_fu_914_p3;
        photons_lane_time_8_reg_1665 <= photons_lane_time_8_fu_985_p3;
        photons_lane_time_reg_1401_pp0_iter2_reg <= photons_lane_time_reg_1401;
        sinces_since_1_reg_1377_pp0_iter2_reg <= sinces_since_1_reg_1377;
        sinces_since_2_reg_1385_pp0_iter2_reg <= sinces_since_2_reg_1385;
        sinces_since_3_reg_1393_pp0_iter2_reg <= sinces_since_3_reg_1393;
        sinces_since_reg_1369_pp0_iter2_reg <= sinces_since_reg_1369;
        tmp_data_V_1_reg_1315_pp0_iter2_reg <= tmp_data_V_1_reg_1315_pp0_iter1_reg;
        tmp_data_V_1_reg_1315_pp0_iter3_reg <= tmp_data_V_1_reg_1315_pp0_iter2_reg;
        tmp_data_V_2_reg_1337_pp0_iter2_reg <= tmp_data_V_2_reg_1337_pp0_iter1_reg;
        tmp_data_V_2_reg_1337_pp0_iter3_reg <= tmp_data_V_2_reg_1337_pp0_iter2_reg;
        tmp_last_V_reg_1332_pp0_iter2_reg <= tmp_last_V_reg_1332_pp0_iter1_reg;
        tmp_last_V_reg_1332_pp0_iter3_reg <= tmp_last_V_reg_1332_pp0_iter2_reg;
        tmp_reg_1342_pp0_iter2_reg <= tmp_reg_1342_pp0_iter1_reg;
        tmp_reg_1342_pp0_iter3_reg <= tmp_reg_1342_pp0_iter2_reg;
        tmp_user_V_1_reg_1324_pp0_iter2_reg <= tmp_user_V_1_reg_1324_pp0_iter1_reg;
        tmp_user_V_1_reg_1324_pp0_iter3_reg <= tmp_user_V_1_reg_1324_pp0_iter2_reg;
        trig_1_reg_1637 <= trig_1_fu_899_p2;
        trig_2_reg_1656 <= trig_2_fu_970_p2;
        trig_3_reg_1675 <= trig_3_fu_1041_p2;
        trig_reg_1618 <= trig_fu_828_p2;
        update_photon_1_reg_1548 <= update_photon_1_fu_657_p2;
        update_photon_2_reg_1577 <= update_photon_2_fu_694_p2;
        update_photon_3_reg_1606 <= update_photon_3_fu_731_p2;
        update_photon_reg_1519 <= update_photon_fu_620_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        photon_cache_lane_phase <= photons_lane_phase_17_fu_1034_p3;
        photon_cache_lane_phase_1 <= photons_lane_phase_15_fu_963_p3;
        photon_cache_lane_phase_2 <= photons_lane_phase_13_fu_892_p3;
        photon_cache_lane_phase_3 <= photons_lane_phase_19_fu_1105_p3;
        photon_cache_lane_time <= photons_lane_time_11_fu_1091_p3;
        photon_cache_lane_time_1 <= photons_lane_time_9_fu_1020_p3;
        photon_cache_lane_time_2 <= photons_lane_time_7_fu_949_p3;
        photon_cache_lane_time_3 <= photons_lane_time_5_fu_878_p3;
        since_cache_since <= sinces_since_11_fu_1077_p3;
        since_cache_since_1 <= sinces_since_9_fu_1006_p3;
        since_cache_since_2 <= sinces_since_7_fu_935_p3;
        since_cache_since_3 <= sinces_since_5_fu_864_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_condition_519)) begin
        if ((xor_ln1069_reg_1350 == 1'd1)) begin
            desync = 1'd1;
        end else if (((xor_ln1069_reg_1350 == 1'd0) & (tmp_last_V_reg_1332 == 1'd1))) begin
            desync = 1'd0;
        end else begin
            desync = 'bx;
        end
    end else begin
        desync = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (xor_ln1069_reg_1350 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (xor_ln1069_reg_1350 == 1'd0) & (tmp_last_V_reg_1332 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        desync_ap_vld = 1'b1;
    end else begin
        desync_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1))) begin
        iq4x_in_TDATA_blk_n = iq4x_in_TVALID_int_regslice;
    end else begin
        iq4x_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        iq4x_in_TREADY_int_regslice = 1'b1;
    end else begin
        iq4x_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1))) begin
        phase4x_in_TDATA_blk_n = phase4x_in_TVALID_int_regslice;
    end else begin
        phase4x_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        phase4x_in_TREADY_int_regslice = 1'b1;
    end else begin
        phase4x_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        photon_data_ce0 = 1'b1;
    end else begin
        photon_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        photon_data_ce1 = 1'b1;
    end else begin
        photon_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        photon_data_we0 = 1'b1;
    end else begin
        photon_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (or_ln97_reg_1623_pp0_iter4_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_reg_1623 == 1'd0)))) begin
        photons_lane_0_TDATA_blk_n = photons_lane_0_TREADY_int_regslice;
    end else begin
        photons_lane_0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_reg_1623 == 1'd0))) begin
        photons_lane_0_TVALID_int_regslice = 1'b1;
    end else begin
        photons_lane_0_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (or_ln97_1_reg_1642_pp0_iter4_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_1_reg_1642 == 1'd0)))) begin
        photons_lane_1_TDATA_blk_n = photons_lane_1_TREADY_int_regslice;
    end else begin
        photons_lane_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_1_reg_1642 == 1'd0))) begin
        photons_lane_1_TVALID_int_regslice = 1'b1;
    end else begin
        photons_lane_1_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (or_ln97_2_reg_1661_pp0_iter4_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_2_reg_1661 == 1'd0)))) begin
        photons_lane_2_TDATA_blk_n = photons_lane_2_TREADY_int_regslice;
    end else begin
        photons_lane_2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_2_reg_1661 == 1'd0))) begin
        photons_lane_2_TVALID_int_regslice = 1'b1;
    end else begin
        photons_lane_2_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (or_ln97_3_reg_1680_pp0_iter4_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_3_reg_1680 == 1'd0)))) begin
        photons_lane_3_TDATA_blk_n = photons_lane_3_TREADY_int_regslice;
    end else begin
        photons_lane_3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (or_ln97_3_reg_1680 == 1'd0))) begin
        photons_lane_3_TVALID_int_regslice = 1'b1;
    end else begin
        photons_lane_3_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        postage_stream_TDATA_blk_n = postage_stream_TREADY_int_regslice;
    end else begin
        postage_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        postage_stream_TVALID_int_regslice = 1'b1;
    end else begin
        postage_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        since_data_ce0 = 1'b1;
    end else begin
        since_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        since_data_ce1 = 1'b1;
    end else begin
        since_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        since_data_we0 = 1'b1;
    end else begin
        since_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        threshoffs_ce0 = 1'b1;
    end else begin
        threshoffs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1))) begin
        timestamp_TDATA_blk_n = timestamp_TVALID_int_regslice;
    end else begin
        timestamp_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        timestamp_TREADY_int_regslice = 1'b1;
    end else begin
        timestamp_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & ((regslice_both_photons_lane_3_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_2_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_1_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_0_U_apdone_blk == 1'b1) | (regslice_both_postage_stream_V_data_V_U_apdone_blk == 1'b1) | (postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680_pp0_iter4_reg == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((or_ln97_2_reg_1661_pp0_iter4_reg == 1'd0) & (photons_lane_2_TREADY_int_regslice == 1'b0)) | ((or_ln97_1_reg_1642_pp0_iter4_reg == 1'd0) & (photons_lane_1_TREADY_int_regslice == 1'b0)) | ((or_ln97_reg_1623_pp0_iter4_reg == 1'd0) & (photons_lane_0_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter4 == 1'b1) & ((postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680 == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((photons_lane_2_TREADY_int_regslice == 1'b0) & (or_ln97_2_reg_1661 == 1'd0)) | ((photons_lane_1_TREADY_int_regslice == 1'b0) & (or_ln97_1_reg_1642 == 1'd0)) | ((photons_lane_0_TREADY_int_regslice == 1'b0) & (or_ln97_reg_1623 == 1'd0)))) | ((1'b1 == 1'b1) & ((timestamp_TVALID_int_regslice == 1'b0) | (iq4x_in_TVALID_int_regslice == 1'b0) | (phase4x_in_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state6_io) | (regslice_both_photons_lane_3_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_2_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_1_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_0_U_apdone_blk == 1'b1) | (regslice_both_postage_stream_V_data_V_U_apdone_blk == 1'b1) | (postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680_pp0_iter4_reg == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((or_ln97_2_reg_1661_pp0_iter4_reg == 1'd0) & (photons_lane_2_TREADY_int_regslice == 1'b0)) | ((or_ln97_1_reg_1642_pp0_iter4_reg == 1'd0) & (photons_lane_1_TREADY_int_regslice == 1'b0)) | ((or_ln97_reg_1623_pp0_iter4_reg == 1'd0) & (photons_lane_0_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter4 == 1'b1) & ((1'b1 == ap_block_state5_io) | (postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680 == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((photons_lane_2_TREADY_int_regslice == 1'b0) & (or_ln97_2_reg_1661 == 1'd0)) | ((photons_lane_1_TREADY_int_regslice == 1'b0) & (or_ln97_1_reg_1642 == 1'd0)) | ((photons_lane_0_TREADY_int_regslice == 1'b0) & (or_ln97_reg_1623 == 1'd0)))) | ((1'b1 == 1'b1) & ((timestamp_TVALID_int_regslice == 1'b0) | (iq4x_in_TVALID_int_regslice == 1'b0) | (phase4x_in_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & ((1'b1 == ap_block_state6_io) | (regslice_both_photons_lane_3_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_2_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_1_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_0_U_apdone_blk == 1'b1) | (regslice_both_postage_stream_V_data_V_U_apdone_blk == 1'b1) | (postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680_pp0_iter4_reg == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((or_ln97_2_reg_1661_pp0_iter4_reg == 1'd0) & (photons_lane_2_TREADY_int_regslice == 1'b0)) | ((or_ln97_1_reg_1642_pp0_iter4_reg == 1'd0) & (photons_lane_1_TREADY_int_regslice == 1'b0)) | ((or_ln97_reg_1623_pp0_iter4_reg == 1'd0) & (photons_lane_0_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter4 == 1'b1) & ((1'b1 == ap_block_state5_io) | (postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680 == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((photons_lane_2_TREADY_int_regslice == 1'b0) & (or_ln97_2_reg_1661 == 1'd0)) | ((photons_lane_1_TREADY_int_regslice == 1'b0) & (or_ln97_1_reg_1642 == 1'd0)) | ((photons_lane_0_TREADY_int_regslice == 1'b0) & (or_ln97_reg_1623 == 1'd0)))) | ((1'b1 == 1'b1) & ((timestamp_TVALID_int_regslice == 1'b0) | (iq4x_in_TVALID_int_regslice == 1'b0) | (phase4x_in_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((timestamp_TVALID_int_regslice == 1'b0) | (iq4x_in_TVALID_int_regslice == 1'b0) | (phase4x_in_TVALID_int_regslice == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680 == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((photons_lane_2_TREADY_int_regslice == 1'b0) & (or_ln97_2_reg_1661 == 1'd0)) | ((photons_lane_1_TREADY_int_regslice == 1'b0) & (or_ln97_1_reg_1642 == 1'd0)) | ((photons_lane_0_TREADY_int_regslice == 1'b0) & (or_ln97_reg_1623 == 1'd0)));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680 == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((photons_lane_2_TREADY_int_regslice == 1'b0) & (or_ln97_2_reg_1661 == 1'd0)) | ((photons_lane_1_TREADY_int_regslice == 1'b0) & (or_ln97_1_reg_1642 == 1'd0)) | ((photons_lane_0_TREADY_int_regslice == 1'b0) & (or_ln97_reg_1623 == 1'd0)));
end

always @ (*) begin
    ap_block_state6_io = ((postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680_pp0_iter4_reg == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((or_ln97_2_reg_1661_pp0_iter4_reg == 1'd0) & (photons_lane_2_TREADY_int_regslice == 1'b0)) | ((or_ln97_1_reg_1642_pp0_iter4_reg == 1'd0) & (photons_lane_1_TREADY_int_regslice == 1'b0)) | ((or_ln97_reg_1623_pp0_iter4_reg == 1'd0) & (photons_lane_0_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((regslice_both_photons_lane_3_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_2_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_1_U_apdone_blk == 1'b1) | (regslice_both_photons_lane_0_U_apdone_blk == 1'b1) | (regslice_both_postage_stream_V_data_V_U_apdone_blk == 1'b1) | (postage_stream_TREADY_int_regslice == 1'b0) | ((or_ln97_3_reg_1680_pp0_iter4_reg == 1'd0) & (photons_lane_3_TREADY_int_regslice == 1'b0)) | ((or_ln97_2_reg_1661_pp0_iter4_reg == 1'd0) & (photons_lane_2_TREADY_int_regslice == 1'b0)) | ((or_ln97_1_reg_1642_pp0_iter4_reg == 1'd0) & (photons_lane_1_TREADY_int_regslice == 1'b0)) | ((or_ln97_reg_1623_pp0_iter4_reg == 1'd0) & (photons_lane_0_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_519 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln1696_1_fu_646_p2 = (($signed(shl_ln884_1_fu_639_p3) > $signed(phase_1_fu_630_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1696_2_fu_683_p2 = (($signed(shl_ln884_2_fu_676_p3) > $signed(phase_2_fu_667_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1696_3_fu_720_p2 = (($signed(shl_ln884_3_fu_713_p3) > $signed(phase_3_fu_704_p4)) ? 1'b1 : 1'b0);

assign icmp_ln1696_fu_609_p2 = (($signed(shl_ln_fu_602_p3) > $signed(phase_fu_599_p1)) ? 1'b1 : 1'b0);

assign icmp_ln90_1_fu_652_p2 = ((sinces_since_1_reg_1377 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln90_2_fu_689_p2 = ((sinces_since_2_reg_1385 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln90_3_fu_726_p2 = ((sinces_since_3_reg_1393 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_615_p2 = ((sinces_since_reg_1369 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln97_1_fu_903_p2 = ((sinces_since_1_reg_1377_pp0_iter2_reg != 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln97_2_fu_974_p2 = ((sinces_since_2_reg_1385_pp0_iter2_reg != 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln97_3_fu_1045_p2 = ((sinces_since_3_reg_1393_pp0_iter2_reg != 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_832_p2 = ((sinces_since_reg_1369_pp0_iter2_reg != 8'd1) ? 1'b1 : 1'b0);

assign iq4x_in_TREADY = regslice_both_iq4x_in_V_data_V_U_ack_in;

assign last_group_fu_594_p2 = ($signed(tmp_user_V_1_reg_1324_pp0_iter1_reg) + $signed(9'd511));

assign new_since_1_fu_662_p2 = ($signed(sinces_since_1_reg_1377) + $signed(8'd255));

assign new_since_2_fu_699_p2 = ($signed(sinces_since_2_reg_1385) + $signed(8'd255));

assign new_since_3_fu_736_p2 = ($signed(sinces_since_3_reg_1393) + $signed(8'd255));

assign new_since_fu_625_p2 = ($signed(sinces_since_reg_1369) + $signed(8'd255));

assign or_ln97_1_fu_908_p2 = (trig_1_fu_899_p2 | icmp_ln97_1_fu_903_p2);

assign or_ln97_2_fu_979_p2 = (trig_2_fu_970_p2 | icmp_ln97_2_fu_974_p2);

assign or_ln97_3_fu_1050_p2 = (trig_3_fu_1041_p2 | icmp_ln97_3_fu_1045_p2);

assign or_ln97_fu_837_p2 = (trig_fu_828_p2 | icmp_ln97_fu_832_p2);

assign phase4x_in_TREADY = regslice_both_phase4x_in_V_data_V_U_ack_in;

assign phase_1_fu_630_p4 = {{tmp_data_V_1_reg_1315_pp0_iter1_reg[31:16]}};

assign phase_2_fu_667_p4 = {{tmp_data_V_1_reg_1315_pp0_iter1_reg[47:32]}};

assign phase_3_fu_704_p4 = {{tmp_data_V_1_reg_1315_pp0_iter1_reg[63:48]}};

assign phase_fu_599_p1 = tmp_data_V_1_reg_1315_pp0_iter1_reg[15:0];

assign photon_data_address0 = zext_ln587_fu_741_p1;

assign photon_data_address1 = zext_ln587_1_fu_405_p1;

assign photon_data_d0 = {{{{{{{{photon_cache_lane_phase_3}, {photon_cache_lane_time}}, {photon_cache_lane_phase}}, {photon_cache_lane_time_1}}, {photon_cache_lane_phase_1}}, {photon_cache_lane_time_2}}, {photon_cache_lane_phase_2}}, {photon_cache_lane_time_3}};

assign photon_out_id_V_1_fu_1214_p2 = (photon_out_id_V_fu_1184_p3 | 11'd1);

assign photon_out_id_V_2_fu_1242_p2 = (photon_out_id_V_fu_1184_p3 | 11'd2);

assign photon_out_id_V_3_fu_1270_p2 = (photon_out_id_V_fu_1184_p3 | 11'd3);

assign photon_out_id_V_fu_1184_p3 = {{tmp_user_V_1_reg_1324_pp0_iter3_reg}, {2'd0}};

assign photon_out_time_V_1_fu_1223_p2 = (tmp_reg_1342_pp0_iter3_reg - zext_ln232_1_fu_1220_p1);

assign photon_out_time_V_2_fu_1251_p2 = (tmp_reg_1342_pp0_iter3_reg - zext_ln232_2_fu_1248_p1);

assign photon_out_time_V_3_fu_1279_p2 = (tmp_reg_1342_pp0_iter3_reg - zext_ln232_3_fu_1276_p1);

assign photon_out_time_V_fu_1194_p2 = (tmp_reg_1342_pp0_iter3_reg - zext_ln232_fu_1191_p1);

assign photons_lane_0_TDATA_int_regslice = tmp_2_fu_1199_p5;

assign photons_lane_0_TVALID = regslice_both_photons_lane_0_U_vld_out;

assign photons_lane_1_TDATA_int_regslice = tmp_5_fu_1228_p4;

assign photons_lane_1_TVALID = regslice_both_photons_lane_1_U_vld_out;

assign photons_lane_2_TDATA_int_regslice = tmp_8_fu_1256_p4;

assign photons_lane_2_TVALID = regslice_both_photons_lane_2_U_vld_out;

assign photons_lane_3_TDATA_int_regslice = tmp_s_fu_1284_p4;

assign photons_lane_3_TVALID = regslice_both_photons_lane_3_U_vld_out;

assign photons_lane_phase_12_fu_848_p3 = ((update_photon_reg_1519[0:0] == 1'b1) ? phase_reg_1502 : photons_lane_phase_reg_1407_pp0_iter2_reg);

assign photons_lane_phase_13_fu_892_p3 = ((xor_ln90_fu_859_p2[0:0] == 1'b1) ? photons_lane_phase_reg_1407_pp0_iter2_reg : select_ln90_4_fu_885_p3);

assign photons_lane_phase_14_fu_919_p3 = ((update_photon_1_reg_1548[0:0] == 1'b1) ? phase_1_reg_1531 : photons_lane_phase_1_reg_1420_pp0_iter2_reg);

assign photons_lane_phase_15_fu_963_p3 = ((xor_ln90_1_fu_930_p2[0:0] == 1'b1) ? photons_lane_phase_1_reg_1420_pp0_iter2_reg : select_ln90_10_fu_956_p3);

assign photons_lane_phase_16_fu_990_p3 = ((update_photon_2_reg_1577[0:0] == 1'b1) ? phase_2_reg_1560 : photons_lane_phase_2_reg_1433_pp0_iter2_reg);

assign photons_lane_phase_17_fu_1034_p3 = ((xor_ln90_2_fu_1001_p2[0:0] == 1'b1) ? photons_lane_phase_2_reg_1433_pp0_iter2_reg : select_ln90_16_fu_1027_p3);

assign photons_lane_phase_18_fu_1061_p3 = ((update_photon_3_reg_1606[0:0] == 1'b1) ? phase_3_reg_1589 : photons_lane_phase_3_reg_1446_pp0_iter2_reg);

assign photons_lane_phase_19_fu_1105_p3 = ((xor_ln90_3_fu_1072_p2[0:0] == 1'b1) ? photons_lane_phase_3_reg_1446_pp0_iter2_reg : select_ln90_22_fu_1098_p3);

assign photons_lane_time_10_fu_1056_p3 = ((update_photon_3_reg_1606[0:0] == 1'b1) ? new_since_3_reg_1612 : photons_lane_time_3_reg_1440_pp0_iter2_reg);

assign photons_lane_time_11_fu_1091_p3 = ((xor_ln90_3_fu_1072_p2[0:0] == 1'b1) ? photons_lane_time_3_reg_1440_pp0_iter2_reg : select_ln90_20_fu_1084_p3);

assign photons_lane_time_4_fu_843_p3 = ((update_photon_reg_1519[0:0] == 1'b1) ? new_since_reg_1525 : photons_lane_time_reg_1401_pp0_iter2_reg);

assign photons_lane_time_5_fu_878_p3 = ((xor_ln90_fu_859_p2[0:0] == 1'b1) ? photons_lane_time_reg_1401_pp0_iter2_reg : select_ln90_2_fu_871_p3);

assign photons_lane_time_6_fu_914_p3 = ((update_photon_1_reg_1548[0:0] == 1'b1) ? new_since_1_reg_1554 : photons_lane_time_1_reg_1414_pp0_iter2_reg);

assign photons_lane_time_7_fu_949_p3 = ((xor_ln90_1_fu_930_p2[0:0] == 1'b1) ? photons_lane_time_1_reg_1414_pp0_iter2_reg : select_ln90_8_fu_942_p3);

assign photons_lane_time_8_fu_985_p3 = ((update_photon_2_reg_1577[0:0] == 1'b1) ? new_since_2_reg_1583 : photons_lane_time_2_reg_1427_pp0_iter2_reg);

assign photons_lane_time_9_fu_1020_p3 = ((xor_ln90_2_fu_1001_p2[0:0] == 1'b1) ? photons_lane_time_2_reg_1427_pp0_iter2_reg : select_ln90_14_fu_1013_p3);

assign photons_lane_time_fu_446_p1 = photon_data_q1[7:0];

assign postage_stream_TDATA_int_regslice = {{tmp_data_V_2_reg_1337_pp0_iter3_reg}, {tmp_data_V_1_reg_1315_pp0_iter3_reg}};

assign postage_stream_TUSER_int_regslice = {{{{{trig_3_reg_1675}, {trig_2_reg_1656}}, {trig_1_reg_1637}}, {trig_reg_1618}}, {tmp_user_V_1_reg_1324_pp0_iter3_reg}};

assign postage_stream_TVALID = regslice_both_postage_stream_V_data_V_U_vld_out;

assign select_ln90_10_fu_956_p3 = ((trig_1_fu_899_p2[0:0] == 1'b1) ? phase_1_reg_1531 : photons_lane_phase_14_fu_919_p3);

assign select_ln90_12_fu_995_p3 = ((trig_2_fu_970_p2[0:0] == 1'b1) ? hoffs_2_reg_1465_pp0_iter2_reg : new_since_2_reg_1583);

assign select_ln90_14_fu_1013_p3 = ((trig_2_fu_970_p2[0:0] == 1'b1) ? hoffs_2_reg_1465_pp0_iter2_reg : photons_lane_time_8_fu_985_p3);

assign select_ln90_16_fu_1027_p3 = ((trig_2_fu_970_p2[0:0] == 1'b1) ? phase_2_reg_1560 : photons_lane_phase_16_fu_990_p3);

assign select_ln90_18_fu_1066_p3 = ((trig_3_fu_1041_p2[0:0] == 1'b1) ? hoffs_3_reg_1471_pp0_iter2_reg : new_since_3_reg_1612);

assign select_ln90_20_fu_1084_p3 = ((trig_3_fu_1041_p2[0:0] == 1'b1) ? hoffs_3_reg_1471_pp0_iter2_reg : photons_lane_time_10_fu_1056_p3);

assign select_ln90_22_fu_1098_p3 = ((trig_3_fu_1041_p2[0:0] == 1'b1) ? phase_3_reg_1589 : photons_lane_phase_18_fu_1061_p3);

assign select_ln90_2_fu_871_p3 = ((trig_fu_828_p2[0:0] == 1'b1) ? hoffs_reg_1453_pp0_iter2_reg : photons_lane_time_4_fu_843_p3);

assign select_ln90_4_fu_885_p3 = ((trig_fu_828_p2[0:0] == 1'b1) ? phase_reg_1502 : photons_lane_phase_12_fu_848_p3);

assign select_ln90_6_fu_924_p3 = ((trig_1_fu_899_p2[0:0] == 1'b1) ? hoffs_1_reg_1459_pp0_iter2_reg : new_since_1_reg_1554);

assign select_ln90_8_fu_942_p3 = ((trig_1_fu_899_p2[0:0] == 1'b1) ? hoffs_1_reg_1459_pp0_iter2_reg : photons_lane_time_6_fu_914_p3);

assign select_ln90_fu_853_p3 = ((trig_fu_828_p2[0:0] == 1'b1) ? hoffs_reg_1453_pp0_iter2_reg : new_since_reg_1525);

assign shl_ln884_1_fu_639_p3 = {{tmp_1_reg_1482}, {8'd0}};

assign shl_ln884_2_fu_676_p3 = {{tmp_3_reg_1487}, {8'd0}};

assign shl_ln884_3_fu_713_p3 = {{tmp_4_reg_1492}, {8'd0}};

assign shl_ln_fu_602_p3 = {{trunc_ln884_reg_1477}, {8'd0}};

assign since_data_address0 = zext_ln587_fu_741_p1;

assign since_data_address1 = zext_ln587_1_fu_405_p1;

assign since_data_d0 = {{{{since_cache_since}, {since_cache_since_1}}, {since_cache_since_2}}, {since_cache_since_3}};

assign sinces_since_11_fu_1077_p3 = ((xor_ln90_3_fu_1072_p2[0:0] == 1'b1) ? sinces_since_3_reg_1393_pp0_iter2_reg : select_ln90_18_fu_1066_p3);

assign sinces_since_5_fu_864_p3 = ((xor_ln90_fu_859_p2[0:0] == 1'b1) ? sinces_since_reg_1369_pp0_iter2_reg : select_ln90_fu_853_p3);

assign sinces_since_7_fu_935_p3 = ((xor_ln90_1_fu_930_p2[0:0] == 1'b1) ? sinces_since_1_reg_1377_pp0_iter2_reg : select_ln90_6_fu_924_p3);

assign sinces_since_9_fu_1006_p3 = ((xor_ln90_2_fu_1001_p2[0:0] == 1'b1) ? sinces_since_2_reg_1385_pp0_iter2_reg : select_ln90_12_fu_995_p3);

assign sinces_since_fu_412_p1 = since_data_q1[7:0];

assign threshoffs_address0 = zext_ln587_1_fu_405_p1;

assign timestamp_TREADY = regslice_both_timestamp_U_ack_in;

assign tmp_2_fu_1199_p5 = {{{{tmp_user_V_1_reg_1324_pp0_iter3_reg}, {2'd0}}, {photons_lane_phase_13_reg_1632}}, {photon_out_time_V_fu_1194_p2}};

assign tmp_5_fu_1228_p4 = {{{photon_out_id_V_1_fu_1214_p2}, {photons_lane_phase_15_reg_1651}}, {photon_out_time_V_1_fu_1223_p2}};

assign tmp_8_fu_1256_p4 = {{{photon_out_id_V_2_fu_1242_p2}, {photons_lane_phase_17_reg_1670}}, {photon_out_time_V_2_fu_1251_p2}};

assign tmp_fu_395_p1 = timestamp_TDATA_int_regslice[35:0];

assign tmp_s_fu_1284_p4 = {{{photon_out_id_V_3_fu_1270_p2}, {photons_lane_phase_19_reg_1689}}, {photon_out_time_V_3_fu_1279_p2}};

assign trig_1_fu_899_p2 = (icmp_ln90_1_reg_1542 & icmp_ln1696_1_reg_1537);

assign trig_2_fu_970_p2 = (icmp_ln90_2_reg_1571 & icmp_ln1696_2_reg_1566);

assign trig_3_fu_1041_p2 = (icmp_ln90_3_reg_1600 & icmp_ln1696_3_reg_1595);

assign trig_fu_828_p2 = (icmp_ln90_reg_1513 & icmp_ln1696_reg_1508);

assign trunc_ln884_fu_560_p1 = threshoffs_q0[7:0];

assign update_photon_1_fu_657_p2 = (($signed(phase_1_fu_630_p4) < $signed(photons_lane_phase_1_reg_1420)) ? 1'b1 : 1'b0);

assign update_photon_2_fu_694_p2 = (($signed(phase_2_fu_667_p4) < $signed(photons_lane_phase_2_reg_1433)) ? 1'b1 : 1'b0);

assign update_photon_3_fu_731_p2 = (($signed(phase_3_fu_704_p4) < $signed(photons_lane_phase_3_reg_1446)) ? 1'b1 : 1'b0);

assign update_photon_fu_620_p2 = (($signed(phase_fu_599_p1) < $signed(photons_lane_phase_reg_1407)) ? 1'b1 : 1'b0);

assign xor_ln1069_fu_399_p2 = (phase4x_in_TLAST_int_regslice ^ iq4x_in_TLAST_int_regslice);

assign xor_ln90_1_fu_930_p2 = (trig_1_fu_899_p2 ^ icmp_ln90_1_reg_1542);

assign xor_ln90_2_fu_1001_p2 = (trig_2_fu_970_p2 ^ icmp_ln90_2_reg_1571);

assign xor_ln90_3_fu_1072_p2 = (trig_3_fu_1041_p2 ^ icmp_ln90_3_reg_1600);

assign xor_ln90_fu_859_p2 = (trig_fu_828_p2 ^ icmp_ln90_reg_1513);

assign zext_ln232_1_fu_1220_p1 = photons_lane_time_6_reg_1646;

assign zext_ln232_2_fu_1248_p1 = photons_lane_time_8_reg_1665;

assign zext_ln232_3_fu_1276_p1 = photons_lane_time_10_reg_1684;

assign zext_ln232_fu_1191_p1 = photons_lane_time_4_reg_1627;

assign zext_ln587_1_fu_405_p1 = phase4x_in_TUSER_int_regslice;

assign zext_ln587_fu_741_p1 = last_group_reg_1497;


reg find_kernel_block = 0;
// synthesis translate_off
`include "trigger_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //trigger

