-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity trigger is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 13;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    instream_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    instream_TVALID : IN STD_LOGIC;
    instream_TREADY : OUT STD_LOGIC;
    instream_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    instream_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    instream_TUSER : IN STD_LOGIC_VECTOR (8 downto 0);
    instream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    outstream_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    outstream_TVALID : OUT STD_LOGIC;
    outstream_TREADY : IN STD_LOGIC;
    outstream_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    outstream_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    outstream_TUSER : OUT STD_LOGIC_VECTOR (12 downto 0);
    outstream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    timestamp_TDATA : IN STD_LOGIC_VECTOR (39 downto 0);
    timestamp_TVALID : IN STD_LOGIC;
    timestamp_TREADY : OUT STD_LOGIC;
    photon_fifos_0_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    photon_fifos_0_TVALID : OUT STD_LOGIC;
    photon_fifos_0_TREADY : IN STD_LOGIC;
    photon_fifos_1_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    photon_fifos_1_TVALID : OUT STD_LOGIC;
    photon_fifos_1_TREADY : IN STD_LOGIC;
    photon_fifos_2_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    photon_fifos_2_TVALID : OUT STD_LOGIC;
    photon_fifos_2_TREADY : IN STD_LOGIC;
    photon_fifos_3_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    photon_fifos_3_TVALID : OUT STD_LOGIC;
    photon_fifos_3_TREADY : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of trigger is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "trigger_trigger,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=1.818000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.237000,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1251,HLS_SYN_LUT=1196,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_const_lv11_3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal threshoffs_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal threshoffs_ce0 : STD_LOGIC;
    signal threshoffs_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal since_cache_since_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal since_cache_since_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal since_cache_since_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal since_cache_since : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal since_data_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal since_data_ce0 : STD_LOGIC;
    signal since_data_we0 : STD_LOGIC;
    signal since_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal since_data_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal since_data_ce1 : STD_LOGIC;
    signal since_data_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal photon_cache_lane_time_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal photon_cache_lane_phase_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal photon_cache_lane_time_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal photon_cache_lane_phase_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal photon_cache_lane_time_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal photon_cache_lane_phase : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal photon_cache_lane_time : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal photon_cache_lane_phase_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal photon_data_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal photon_data_ce0 : STD_LOGIC;
    signal photon_data_we0 : STD_LOGIC;
    signal photon_data_d0 : STD_LOGIC_VECTOR (95 downto 0);
    signal photon_data_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal photon_data_ce1 : STD_LOGIC;
    signal photon_data_q1 : STD_LOGIC_VECTOR (95 downto 0);
    signal instream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal outstream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal timestamp_TDATA_blk_n : STD_LOGIC;
    signal photon_fifos_0_TDATA_blk_n : STD_LOGIC;
    signal or_ln91_reg_1544 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_reg_1544_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal photon_fifos_1_TDATA_blk_n : STD_LOGIC;
    signal or_ln91_1_reg_1563 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_1_reg_1563_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal photon_fifos_2_TDATA_blk_n : STD_LOGIC;
    signal or_ln91_2_reg_1582 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_2_reg_1582_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal photon_fifos_3_TDATA_blk_n : STD_LOGIC;
    signal or_ln91_3_reg_1601 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_3_reg_1601_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_reg_1244 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal regslice_both_outstream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_photon_fifos_0_U_apdone_blk : STD_LOGIC;
    signal regslice_both_photon_fifos_1_U_apdone_blk : STD_LOGIC;
    signal regslice_both_photon_fifos_2_U_apdone_blk : STD_LOGIC;
    signal regslice_both_photon_fifos_3_U_apdone_blk : STD_LOGIC;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_data_V_reg_1244_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_data_V_reg_1244_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_data_V_reg_1244_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_user_V_1_reg_1252 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_user_V_1_reg_1252_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_user_V_1_reg_1252_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_user_V_1_reg_1252_pp0_iter3_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_last_V_reg_1260 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_1260_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_1260_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_1260_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_338_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_reg_1265 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_reg_1265_pp0_iter1_reg : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_reg_1265_pp0_iter2_reg : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_reg_1265_pp0_iter3_reg : STD_LOGIC_VECTOR (35 downto 0);
    signal phase_fu_349_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal phase_reg_1288 : STD_LOGIC_VECTOR (15 downto 0);
    signal phase_reg_1288_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal phase_reg_1288_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sinces_since_fu_353_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_reg_1296 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_reg_1296_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_1_reg_1304 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_1_reg_1304_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_2_reg_1312 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_2_reg_1312_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_3_reg_1320 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_3_reg_1320_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_fu_387_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_reg_1328 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_reg_1328_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_reg_1334 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_reg_1334_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_time_1_reg_1341 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_1_reg_1341_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_1_reg_1347 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_1_reg_1347_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_time_2_reg_1354 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_2_reg_1354_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_2_reg_1360 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_2_reg_1360_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_time_3_reg_1367 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_3_reg_1367_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_3_reg_1373 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_3_reg_1373_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal hoffs_reg_1380 : STD_LOGIC_VECTOR (7 downto 0);
    signal hoffs_reg_1380_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal hoffs_1_reg_1386 : STD_LOGIC_VECTOR (7 downto 0);
    signal hoffs_1_reg_1386_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal hoffs_2_reg_1392 : STD_LOGIC_VECTOR (7 downto 0);
    signal hoffs_2_reg_1392_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal hoffs_3_reg_1398 : STD_LOGIC_VECTOR (7 downto 0);
    signal hoffs_3_reg_1398_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln884_fu_501_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln884_reg_1404 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_1409 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_reg_1414 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_1419 : STD_LOGIC_VECTOR (7 downto 0);
    signal last_group_fu_535_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal last_group_reg_1424 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln1696_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1696_reg_1429 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_1434 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_reg_1440 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_since_fu_561_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal new_since_reg_1446 : STD_LOGIC_VECTOR (7 downto 0);
    signal phase_1_fu_566_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal phase_1_reg_1452 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1696_1_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1696_1_reg_1458 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_1_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_1_reg_1463 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_1_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_1_reg_1469 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_since_1_fu_598_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal new_since_1_reg_1475 : STD_LOGIC_VECTOR (7 downto 0);
    signal phase_2_fu_603_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal phase_2_reg_1481 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1696_2_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1696_2_reg_1487 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_2_fu_625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_2_reg_1492 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_2_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_2_reg_1498 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_since_2_fu_635_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal new_since_2_reg_1504 : STD_LOGIC_VECTOR (7 downto 0);
    signal phase_3_fu_640_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal phase_3_reg_1510 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1696_3_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1696_3_reg_1516 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_3_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_3_reg_1521 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_3_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal update_photon_3_reg_1527 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_since_3_fu_672_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal new_since_3_reg_1533 : STD_LOGIC_VECTOR (7 downto 0);
    signal trig_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trig_reg_1539 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal photons_lane_time_4_fu_779_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_4_reg_1548 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_13_fu_828_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_13_reg_1553 : STD_LOGIC_VECTOR (15 downto 0);
    signal trig_1_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trig_1_reg_1558 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_1_fu_844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal photons_lane_time_6_fu_850_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_6_reg_1567 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_15_fu_899_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_15_reg_1572 : STD_LOGIC_VECTOR (15 downto 0);
    signal trig_2_fu_906_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trig_2_reg_1577 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_2_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal photons_lane_time_8_fu_921_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_8_reg_1586 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_17_fu_970_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_17_reg_1591 : STD_LOGIC_VECTOR (15 downto 0);
    signal trig_3_fu_977_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trig_3_reg_1596 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_3_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal photons_lane_time_10_fu_992_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_10_reg_1605 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_19_fu_1041_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal photons_lane_phase_19_reg_1610 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal zext_ln587_1_fu_342_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_fu_677_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sinces_since_5_fu_800_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_7_fu_871_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_9_fu_942_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sinces_since_11_fu_1013_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_5_fu_814_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_7_fu_885_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_9_fu_956_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_time_11_fu_1027_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal shl_ln_fu_540_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln884_1_fu_575_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln884_2_fu_612_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln884_3_fu_649_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln91_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln84_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_fu_789_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln84_2_fu_807_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_12_fu_784_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln84_4_fu_821_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln91_1_fu_839_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln84_1_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_6_fu_860_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln84_8_fu_878_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_14_fu_855_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln84_10_fu_892_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln91_2_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln84_2_fu_937_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_12_fu_931_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln84_14_fu_949_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_16_fu_926_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln84_16_fu_963_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln91_3_fu_981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln84_3_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_18_fu_1002_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln84_20_fu_1020_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal photons_lane_phase_18_fu_997_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln84_22_fu_1034_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln232_fu_1127_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal photon_out_time_V_fu_1130_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_2_fu_1135_p5 : STD_LOGIC_VECTOR (62 downto 0);
    signal photon_out_id_V_fu_1120_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln232_1_fu_1156_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal photon_out_id_V_1_fu_1150_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal photon_out_time_V_1_fu_1159_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_5_fu_1164_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln232_2_fu_1184_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal photon_out_id_V_2_fu_1178_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal photon_out_time_V_2_fu_1187_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_8_fu_1192_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln232_3_fu_1212_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal photon_out_id_V_3_fu_1206_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal photon_out_time_V_3_fu_1215_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_s_fu_1220_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_instream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal instream_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal instream_TVALID_int_regslice : STD_LOGIC;
    signal instream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_instream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_instream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal instream_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_instream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_instream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_instream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal instream_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_instream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_instream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_instream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal instream_TUSER_int_regslice : STD_LOGIC_VECTOR (8 downto 0);
    signal regslice_both_instream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_instream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_instream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal instream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_instream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_instream_V_last_V_U_ack_in : STD_LOGIC;
    signal outstream_TVALID_int_regslice : STD_LOGIC;
    signal outstream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_outstream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outstream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outstream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outstream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outstream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outstream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outstream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outstream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal outstream_TUSER_int_regslice : STD_LOGIC_VECTOR (12 downto 0);
    signal regslice_both_outstream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outstream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outstream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outstream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outstream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_timestamp_U_apdone_blk : STD_LOGIC;
    signal timestamp_TDATA_int_regslice : STD_LOGIC_VECTOR (39 downto 0);
    signal timestamp_TVALID_int_regslice : STD_LOGIC;
    signal timestamp_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_timestamp_U_ack_in : STD_LOGIC;
    signal photon_fifos_0_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal photon_fifos_0_TVALID_int_regslice : STD_LOGIC;
    signal photon_fifos_0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_photon_fifos_0_U_vld_out : STD_LOGIC;
    signal photon_fifos_1_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal photon_fifos_1_TVALID_int_regslice : STD_LOGIC;
    signal photon_fifos_1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_photon_fifos_1_U_vld_out : STD_LOGIC;
    signal photon_fifos_2_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal photon_fifos_2_TVALID_int_regslice : STD_LOGIC;
    signal photon_fifos_2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_photon_fifos_2_U_vld_out : STD_LOGIC;
    signal photon_fifos_3_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal photon_fifos_3_TVALID_int_regslice : STD_LOGIC;
    signal photon_fifos_3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_photon_fifos_3_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component trigger_since_data_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component trigger_photon_data_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (95 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (95 downto 0) );
    end component;


    component trigger_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        threshoffs_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        threshoffs_ce0 : IN STD_LOGIC;
        threshoffs_q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component trigger_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    since_data_U : component trigger_since_data_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => since_data_address0,
        ce0 => since_data_ce0,
        we0 => since_data_we0,
        d0 => since_data_d0,
        address1 => since_data_address1,
        ce1 => since_data_ce1,
        q1 => since_data_q1);

    photon_data_U : component trigger_photon_data_RAM_AUTO_1R1W
    generic map (
        DataWidth => 96,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => photon_data_address0,
        ce0 => photon_data_ce0,
        we0 => photon_data_we0,
        d0 => photon_data_d0,
        address1 => photon_data_address1,
        ce1 => photon_data_ce1,
        q1 => photon_data_q1);

    control_s_axi_U : component trigger_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        threshoffs_address0 => threshoffs_address0,
        threshoffs_ce0 => threshoffs_ce0,
        threshoffs_q0 => threshoffs_q0);

    regslice_both_instream_V_data_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => instream_TDATA,
        vld_in => instream_TVALID,
        ack_in => regslice_both_instream_V_data_V_U_ack_in,
        data_out => instream_TDATA_int_regslice,
        vld_out => instream_TVALID_int_regslice,
        ack_out => instream_TREADY_int_regslice,
        apdone_blk => regslice_both_instream_V_data_V_U_apdone_blk);

    regslice_both_instream_V_keep_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => instream_TKEEP,
        vld_in => instream_TVALID,
        ack_in => regslice_both_instream_V_keep_V_U_ack_in,
        data_out => instream_TKEEP_int_regslice,
        vld_out => regslice_both_instream_V_keep_V_U_vld_out,
        ack_out => instream_TREADY_int_regslice,
        apdone_blk => regslice_both_instream_V_keep_V_U_apdone_blk);

    regslice_both_instream_V_strb_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => instream_TSTRB,
        vld_in => instream_TVALID,
        ack_in => regslice_both_instream_V_strb_V_U_ack_in,
        data_out => instream_TSTRB_int_regslice,
        vld_out => regslice_both_instream_V_strb_V_U_vld_out,
        ack_out => instream_TREADY_int_regslice,
        apdone_blk => regslice_both_instream_V_strb_V_U_apdone_blk);

    regslice_both_instream_V_user_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 9)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => instream_TUSER,
        vld_in => instream_TVALID,
        ack_in => regslice_both_instream_V_user_V_U_ack_in,
        data_out => instream_TUSER_int_regslice,
        vld_out => regslice_both_instream_V_user_V_U_vld_out,
        ack_out => instream_TREADY_int_regslice,
        apdone_blk => regslice_both_instream_V_user_V_U_apdone_blk);

    regslice_both_instream_V_last_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => instream_TLAST,
        vld_in => instream_TVALID,
        ack_in => regslice_both_instream_V_last_V_U_ack_in,
        data_out => instream_TLAST_int_regslice,
        vld_out => regslice_both_instream_V_last_V_U_vld_out,
        ack_out => instream_TREADY_int_regslice,
        apdone_blk => regslice_both_instream_V_last_V_U_apdone_blk);

    regslice_both_outstream_V_data_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_data_V_reg_1244_pp0_iter3_reg,
        vld_in => outstream_TVALID_int_regslice,
        ack_in => outstream_TREADY_int_regslice,
        data_out => outstream_TDATA,
        vld_out => regslice_both_outstream_V_data_V_U_vld_out,
        ack_out => outstream_TREADY,
        apdone_blk => regslice_both_outstream_V_data_V_U_apdone_blk);

    regslice_both_outstream_V_keep_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv8_0,
        vld_in => outstream_TVALID_int_regslice,
        ack_in => regslice_both_outstream_V_keep_V_U_ack_in_dummy,
        data_out => outstream_TKEEP,
        vld_out => regslice_both_outstream_V_keep_V_U_vld_out,
        ack_out => outstream_TREADY,
        apdone_blk => regslice_both_outstream_V_keep_V_U_apdone_blk);

    regslice_both_outstream_V_strb_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv8_0,
        vld_in => outstream_TVALID_int_regslice,
        ack_in => regslice_both_outstream_V_strb_V_U_ack_in_dummy,
        data_out => outstream_TSTRB,
        vld_out => regslice_both_outstream_V_strb_V_U_vld_out,
        ack_out => outstream_TREADY,
        apdone_blk => regslice_both_outstream_V_strb_V_U_apdone_blk);

    regslice_both_outstream_V_user_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 13)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => outstream_TUSER_int_regslice,
        vld_in => outstream_TVALID_int_regslice,
        ack_in => regslice_both_outstream_V_user_V_U_ack_in_dummy,
        data_out => outstream_TUSER,
        vld_out => regslice_both_outstream_V_user_V_U_vld_out,
        ack_out => outstream_TREADY,
        apdone_blk => regslice_both_outstream_V_user_V_U_apdone_blk);

    regslice_both_outstream_V_last_V_U : component trigger_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_V_reg_1260_pp0_iter3_reg,
        vld_in => outstream_TVALID_int_regslice,
        ack_in => regslice_both_outstream_V_last_V_U_ack_in_dummy,
        data_out => outstream_TLAST,
        vld_out => regslice_both_outstream_V_last_V_U_vld_out,
        ack_out => outstream_TREADY,
        apdone_blk => regslice_both_outstream_V_last_V_U_apdone_blk);

    regslice_both_timestamp_U : component trigger_regslice_both
    generic map (
        DataWidth => 40)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => timestamp_TDATA,
        vld_in => timestamp_TVALID,
        ack_in => regslice_both_timestamp_U_ack_in,
        data_out => timestamp_TDATA_int_regslice,
        vld_out => timestamp_TVALID_int_regslice,
        ack_out => timestamp_TREADY_int_regslice,
        apdone_blk => regslice_both_timestamp_U_apdone_blk);

    regslice_both_photon_fifos_0_U : component trigger_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => photon_fifos_0_TDATA_int_regslice,
        vld_in => photon_fifos_0_TVALID_int_regslice,
        ack_in => photon_fifos_0_TREADY_int_regslice,
        data_out => photon_fifos_0_TDATA,
        vld_out => regslice_both_photon_fifos_0_U_vld_out,
        ack_out => photon_fifos_0_TREADY,
        apdone_blk => regslice_both_photon_fifos_0_U_apdone_blk);

    regslice_both_photon_fifos_1_U : component trigger_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => photon_fifos_1_TDATA_int_regslice,
        vld_in => photon_fifos_1_TVALID_int_regslice,
        ack_in => photon_fifos_1_TREADY_int_regslice,
        data_out => photon_fifos_1_TDATA,
        vld_out => regslice_both_photon_fifos_1_U_vld_out,
        ack_out => photon_fifos_1_TREADY,
        apdone_blk => regslice_both_photon_fifos_1_U_apdone_blk);

    regslice_both_photon_fifos_2_U : component trigger_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => photon_fifos_2_TDATA_int_regslice,
        vld_in => photon_fifos_2_TVALID_int_regslice,
        ack_in => photon_fifos_2_TREADY_int_regslice,
        data_out => photon_fifos_2_TDATA,
        vld_out => regslice_both_photon_fifos_2_U_vld_out,
        ack_out => photon_fifos_2_TREADY,
        apdone_blk => regslice_both_photon_fifos_2_U_apdone_blk);

    regslice_both_photon_fifos_3_U : component trigger_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => photon_fifos_3_TDATA_int_regslice,
        vld_in => photon_fifos_3_TVALID_int_regslice,
        ack_in => photon_fifos_3_TREADY_int_regslice,
        data_out => photon_fifos_3_TDATA,
        vld_out => regslice_both_photon_fifos_3_U_vld_out,
        ack_out => photon_fifos_3_TREADY,
        apdone_blk => regslice_both_photon_fifos_3_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                hoffs_1_reg_1386 <= threshoffs_q0(31 downto 24);
                hoffs_2_reg_1392 <= threshoffs_q0(47 downto 40);
                hoffs_3_reg_1398 <= threshoffs_q0(63 downto 56);
                hoffs_reg_1380 <= threshoffs_q0(15 downto 8);
                phase_reg_1288 <= phase_fu_349_p1;
                phase_reg_1288_pp0_iter1_reg <= phase_reg_1288;
                photons_lane_phase_1_reg_1347 <= photon_data_q1(47 downto 32);
                photons_lane_phase_2_reg_1360 <= photon_data_q1(71 downto 56);
                photons_lane_phase_3_reg_1373 <= photon_data_q1(95 downto 80);
                photons_lane_phase_reg_1334 <= photon_data_q1(23 downto 8);
                photons_lane_time_1_reg_1341 <= photon_data_q1(31 downto 24);
                photons_lane_time_2_reg_1354 <= photon_data_q1(55 downto 48);
                photons_lane_time_3_reg_1367 <= photon_data_q1(79 downto 72);
                photons_lane_time_reg_1328 <= photons_lane_time_fu_387_p1;
                sinces_since_1_reg_1304 <= since_data_q1(15 downto 8);
                sinces_since_2_reg_1312 <= since_data_q1(23 downto 16);
                sinces_since_3_reg_1320 <= since_data_q1(31 downto 24);
                sinces_since_reg_1296 <= sinces_since_fu_353_p1;
                tmp_1_reg_1409 <= threshoffs_q0(23 downto 16);
                tmp_3_reg_1414 <= threshoffs_q0(39 downto 32);
                tmp_4_reg_1419 <= threshoffs_q0(55 downto 48);
                tmp_data_V_reg_1244 <= instream_TDATA_int_regslice;
                tmp_data_V_reg_1244_pp0_iter1_reg <= tmp_data_V_reg_1244;
                tmp_last_V_reg_1260 <= instream_TLAST_int_regslice;
                tmp_last_V_reg_1260_pp0_iter1_reg <= tmp_last_V_reg_1260;
                tmp_reg_1265 <= tmp_fu_338_p1;
                tmp_reg_1265_pp0_iter1_reg <= tmp_reg_1265;
                tmp_user_V_1_reg_1252 <= instream_TUSER_int_regslice;
                tmp_user_V_1_reg_1252_pp0_iter1_reg <= tmp_user_V_1_reg_1252;
                trunc_ln884_reg_1404 <= trunc_ln884_fu_501_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                hoffs_1_reg_1386_pp0_iter2_reg <= hoffs_1_reg_1386;
                hoffs_2_reg_1392_pp0_iter2_reg <= hoffs_2_reg_1392;
                hoffs_3_reg_1398_pp0_iter2_reg <= hoffs_3_reg_1398;
                hoffs_reg_1380_pp0_iter2_reg <= hoffs_reg_1380;
                icmp_ln1696_1_reg_1458 <= icmp_ln1696_1_fu_582_p2;
                icmp_ln1696_2_reg_1487 <= icmp_ln1696_2_fu_619_p2;
                icmp_ln1696_3_reg_1516 <= icmp_ln1696_3_fu_656_p2;
                icmp_ln1696_reg_1429 <= icmp_ln1696_fu_547_p2;
                icmp_ln84_1_reg_1463 <= icmp_ln84_1_fu_588_p2;
                icmp_ln84_2_reg_1492 <= icmp_ln84_2_fu_625_p2;
                icmp_ln84_3_reg_1521 <= icmp_ln84_3_fu_662_p2;
                icmp_ln84_reg_1434 <= icmp_ln84_fu_552_p2;
                last_group_reg_1424 <= last_group_fu_535_p2;
                new_since_1_reg_1475 <= new_since_1_fu_598_p2;
                new_since_2_reg_1504 <= new_since_2_fu_635_p2;
                new_since_3_reg_1533 <= new_since_3_fu_672_p2;
                new_since_reg_1446 <= new_since_fu_561_p2;
                or_ln91_1_reg_1563 <= or_ln91_1_fu_844_p2;
                or_ln91_1_reg_1563_pp0_iter4_reg <= or_ln91_1_reg_1563;
                or_ln91_2_reg_1582 <= or_ln91_2_fu_915_p2;
                or_ln91_2_reg_1582_pp0_iter4_reg <= or_ln91_2_reg_1582;
                or_ln91_3_reg_1601 <= or_ln91_3_fu_986_p2;
                or_ln91_3_reg_1601_pp0_iter4_reg <= or_ln91_3_reg_1601;
                or_ln91_reg_1544 <= or_ln91_fu_773_p2;
                or_ln91_reg_1544_pp0_iter4_reg <= or_ln91_reg_1544;
                phase_1_reg_1452 <= tmp_data_V_reg_1244_pp0_iter1_reg(31 downto 16);
                phase_2_reg_1481 <= tmp_data_V_reg_1244_pp0_iter1_reg(47 downto 32);
                phase_3_reg_1510 <= tmp_data_V_reg_1244_pp0_iter1_reg(63 downto 48);
                phase_reg_1288_pp0_iter2_reg <= phase_reg_1288_pp0_iter1_reg;
                photons_lane_phase_13_reg_1553 <= photons_lane_phase_13_fu_828_p3;
                photons_lane_phase_15_reg_1572 <= photons_lane_phase_15_fu_899_p3;
                photons_lane_phase_17_reg_1591 <= photons_lane_phase_17_fu_970_p3;
                photons_lane_phase_19_reg_1610 <= photons_lane_phase_19_fu_1041_p3;
                photons_lane_phase_1_reg_1347_pp0_iter2_reg <= photons_lane_phase_1_reg_1347;
                photons_lane_phase_2_reg_1360_pp0_iter2_reg <= photons_lane_phase_2_reg_1360;
                photons_lane_phase_3_reg_1373_pp0_iter2_reg <= photons_lane_phase_3_reg_1373;
                photons_lane_phase_reg_1334_pp0_iter2_reg <= photons_lane_phase_reg_1334;
                photons_lane_time_10_reg_1605 <= photons_lane_time_10_fu_992_p3;
                photons_lane_time_1_reg_1341_pp0_iter2_reg <= photons_lane_time_1_reg_1341;
                photons_lane_time_2_reg_1354_pp0_iter2_reg <= photons_lane_time_2_reg_1354;
                photons_lane_time_3_reg_1367_pp0_iter2_reg <= photons_lane_time_3_reg_1367;
                photons_lane_time_4_reg_1548 <= photons_lane_time_4_fu_779_p3;
                photons_lane_time_6_reg_1567 <= photons_lane_time_6_fu_850_p3;
                photons_lane_time_8_reg_1586 <= photons_lane_time_8_fu_921_p3;
                photons_lane_time_reg_1328_pp0_iter2_reg <= photons_lane_time_reg_1328;
                sinces_since_1_reg_1304_pp0_iter2_reg <= sinces_since_1_reg_1304;
                sinces_since_2_reg_1312_pp0_iter2_reg <= sinces_since_2_reg_1312;
                sinces_since_3_reg_1320_pp0_iter2_reg <= sinces_since_3_reg_1320;
                sinces_since_reg_1296_pp0_iter2_reg <= sinces_since_reg_1296;
                tmp_data_V_reg_1244_pp0_iter2_reg <= tmp_data_V_reg_1244_pp0_iter1_reg;
                tmp_data_V_reg_1244_pp0_iter3_reg <= tmp_data_V_reg_1244_pp0_iter2_reg;
                tmp_last_V_reg_1260_pp0_iter2_reg <= tmp_last_V_reg_1260_pp0_iter1_reg;
                tmp_last_V_reg_1260_pp0_iter3_reg <= tmp_last_V_reg_1260_pp0_iter2_reg;
                tmp_reg_1265_pp0_iter2_reg <= tmp_reg_1265_pp0_iter1_reg;
                tmp_reg_1265_pp0_iter3_reg <= tmp_reg_1265_pp0_iter2_reg;
                tmp_user_V_1_reg_1252_pp0_iter2_reg <= tmp_user_V_1_reg_1252_pp0_iter1_reg;
                tmp_user_V_1_reg_1252_pp0_iter3_reg <= tmp_user_V_1_reg_1252_pp0_iter2_reg;
                trig_1_reg_1558 <= trig_1_fu_835_p2;
                trig_2_reg_1577 <= trig_2_fu_906_p2;
                trig_3_reg_1596 <= trig_3_fu_977_p2;
                trig_reg_1539 <= trig_fu_764_p2;
                update_photon_1_reg_1469 <= update_photon_1_fu_593_p2;
                update_photon_2_reg_1498 <= update_photon_2_fu_630_p2;
                update_photon_3_reg_1527 <= update_photon_3_fu_667_p2;
                update_photon_reg_1440 <= update_photon_fu_557_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                photon_cache_lane_phase <= photons_lane_phase_17_fu_970_p3;
                photon_cache_lane_phase_1 <= photons_lane_phase_15_fu_899_p3;
                photon_cache_lane_phase_2 <= photons_lane_phase_13_fu_828_p3;
                photon_cache_lane_phase_3 <= photons_lane_phase_19_fu_1041_p3;
                photon_cache_lane_time <= photons_lane_time_11_fu_1027_p3;
                photon_cache_lane_time_1 <= photons_lane_time_9_fu_956_p3;
                photon_cache_lane_time_2 <= photons_lane_time_7_fu_885_p3;
                photon_cache_lane_time_3 <= photons_lane_time_5_fu_814_p3;
                since_cache_since <= sinces_since_11_fu_1013_p3;
                since_cache_since_1 <= sinces_since_9_fu_942_p3;
                since_cache_since_2 <= sinces_since_7_fu_871_p3;
                since_cache_since_3 <= sinces_since_5_fu_800_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, or_ln91_reg_1544, or_ln91_reg_1544_pp0_iter4_reg, or_ln91_1_reg_1563, or_ln91_1_reg_1563_pp0_iter4_reg, or_ln91_2_reg_1582, or_ln91_2_reg_1582_pp0_iter4_reg, or_ln91_3_reg_1601, or_ln91_3_reg_1601_pp0_iter4_reg, regslice_both_outstream_V_data_V_U_apdone_blk, regslice_both_photon_fifos_0_U_apdone_blk, regslice_both_photon_fifos_1_U_apdone_blk, regslice_both_photon_fifos_2_U_apdone_blk, regslice_both_photon_fifos_3_U_apdone_blk, instream_TVALID_int_regslice, outstream_TREADY_int_regslice, timestamp_TVALID_int_regslice, photon_fifos_0_TREADY_int_regslice, photon_fifos_1_TREADY_int_regslice, photon_fifos_2_TREADY_int_regslice, photon_fifos_3_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_const_logic_1 = ap_const_logic_1) and ((timestamp_TVALID_int_regslice = ap_const_logic_0) or (instream_TVALID_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_photon_fifos_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_0_U_apdone_blk = ap_const_logic_1) or (regslice_both_outstream_V_data_V_U_apdone_blk = ap_const_logic_1) or (outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544_pp0_iter4_reg = ap_const_lv1_0)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601 = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582 = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563 = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544 = ap_const_lv1_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, or_ln91_reg_1544, or_ln91_reg_1544_pp0_iter4_reg, or_ln91_1_reg_1563, or_ln91_1_reg_1563_pp0_iter4_reg, or_ln91_2_reg_1582, or_ln91_2_reg_1582_pp0_iter4_reg, or_ln91_3_reg_1601, or_ln91_3_reg_1601_pp0_iter4_reg, ap_block_state5_io, regslice_both_outstream_V_data_V_U_apdone_blk, regslice_both_photon_fifos_0_U_apdone_blk, regslice_both_photon_fifos_1_U_apdone_blk, regslice_both_photon_fifos_2_U_apdone_blk, regslice_both_photon_fifos_3_U_apdone_blk, ap_block_state6_io, instream_TVALID_int_regslice, outstream_TREADY_int_regslice, timestamp_TVALID_int_regslice, photon_fifos_0_TREADY_int_regslice, photon_fifos_1_TREADY_int_regslice, photon_fifos_2_TREADY_int_regslice, photon_fifos_3_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_logic_1 = ap_const_logic_1) and ((timestamp_TVALID_int_regslice = ap_const_logic_0) or (instream_TVALID_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or (regslice_both_photon_fifos_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_0_U_apdone_blk = ap_const_logic_1) or (regslice_both_outstream_V_data_V_U_apdone_blk = ap_const_logic_1) or (outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544_pp0_iter4_reg = ap_const_lv1_0)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601 = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582 = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563 = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544 = ap_const_lv1_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, or_ln91_reg_1544, or_ln91_reg_1544_pp0_iter4_reg, or_ln91_1_reg_1563, or_ln91_1_reg_1563_pp0_iter4_reg, or_ln91_2_reg_1582, or_ln91_2_reg_1582_pp0_iter4_reg, or_ln91_3_reg_1601, or_ln91_3_reg_1601_pp0_iter4_reg, ap_block_state5_io, regslice_both_outstream_V_data_V_U_apdone_blk, regslice_both_photon_fifos_0_U_apdone_blk, regslice_both_photon_fifos_1_U_apdone_blk, regslice_both_photon_fifos_2_U_apdone_blk, regslice_both_photon_fifos_3_U_apdone_blk, ap_block_state6_io, instream_TVALID_int_regslice, outstream_TREADY_int_regslice, timestamp_TVALID_int_regslice, photon_fifos_0_TREADY_int_regslice, photon_fifos_1_TREADY_int_regslice, photon_fifos_2_TREADY_int_regslice, photon_fifos_3_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_logic_1 = ap_const_logic_1) and ((timestamp_TVALID_int_regslice = ap_const_logic_0) or (instream_TVALID_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or (regslice_both_photon_fifos_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_0_U_apdone_blk = ap_const_logic_1) or (regslice_both_outstream_V_data_V_U_apdone_blk = ap_const_logic_1) or (outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544_pp0_iter4_reg = ap_const_lv1_0)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601 = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582 = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563 = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544 = ap_const_lv1_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(instream_TVALID_int_regslice, timestamp_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((timestamp_TVALID_int_regslice = ap_const_logic_0) or (instream_TVALID_int_regslice = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_io_assign_proc : process(or_ln91_reg_1544, or_ln91_1_reg_1563, or_ln91_2_reg_1582, or_ln91_3_reg_1601, outstream_TREADY_int_regslice, photon_fifos_0_TREADY_int_regslice, photon_fifos_1_TREADY_int_regslice, photon_fifos_2_TREADY_int_regslice, photon_fifos_3_TREADY_int_regslice)
    begin
                ap_block_state5_io <= ((outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601 = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582 = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563 = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544 = ap_const_lv1_0)));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(or_ln91_reg_1544, or_ln91_1_reg_1563, or_ln91_2_reg_1582, or_ln91_3_reg_1601, outstream_TREADY_int_regslice, photon_fifos_0_TREADY_int_regslice, photon_fifos_1_TREADY_int_regslice, photon_fifos_2_TREADY_int_regslice, photon_fifos_3_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601 = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582 = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563 = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544 = ap_const_lv1_0)));
    end process;


    ap_block_state6_io_assign_proc : process(or_ln91_reg_1544_pp0_iter4_reg, or_ln91_1_reg_1563_pp0_iter4_reg, or_ln91_2_reg_1582_pp0_iter4_reg, or_ln91_3_reg_1601_pp0_iter4_reg, outstream_TREADY_int_regslice, photon_fifos_0_TREADY_int_regslice, photon_fifos_1_TREADY_int_regslice, photon_fifos_2_TREADY_int_regslice, photon_fifos_3_TREADY_int_regslice)
    begin
                ap_block_state6_io <= ((outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544_pp0_iter4_reg = ap_const_lv1_0)));
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(or_ln91_reg_1544_pp0_iter4_reg, or_ln91_1_reg_1563_pp0_iter4_reg, or_ln91_2_reg_1582_pp0_iter4_reg, or_ln91_3_reg_1601_pp0_iter4_reg, regslice_both_outstream_V_data_V_U_apdone_blk, regslice_both_photon_fifos_0_U_apdone_blk, regslice_both_photon_fifos_1_U_apdone_blk, regslice_both_photon_fifos_2_U_apdone_blk, regslice_both_photon_fifos_3_U_apdone_blk, outstream_TREADY_int_regslice, photon_fifos_0_TREADY_int_regslice, photon_fifos_1_TREADY_int_regslice, photon_fifos_2_TREADY_int_regslice, photon_fifos_3_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter5 <= ((regslice_both_photon_fifos_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_photon_fifos_0_U_apdone_blk = ap_const_logic_1) or (regslice_both_outstream_V_data_V_U_apdone_blk = ap_const_logic_1) or (outstream_TREADY_int_regslice = ap_const_logic_0) or ((or_ln91_3_reg_1601_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_3_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_2_reg_1582_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_2_TREADY_int_regslice = ap_const_logic_0)) or ((or_ln91_1_reg_1563_pp0_iter4_reg = ap_const_lv1_0) and (photon_fifos_1_TREADY_int_regslice = ap_const_logic_0)) or ((photon_fifos_0_TREADY_int_regslice = ap_const_logic_0) and (or_ln91_reg_1544_pp0_iter4_reg = ap_const_lv1_0)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    icmp_ln1696_1_fu_582_p2 <= "1" when (signed(shl_ln884_1_fu_575_p3) > signed(phase_1_fu_566_p4)) else "0";
    icmp_ln1696_2_fu_619_p2 <= "1" when (signed(shl_ln884_2_fu_612_p3) > signed(phase_2_fu_603_p4)) else "0";
    icmp_ln1696_3_fu_656_p2 <= "1" when (signed(shl_ln884_3_fu_649_p3) > signed(phase_3_fu_640_p4)) else "0";
    icmp_ln1696_fu_547_p2 <= "1" when (signed(shl_ln_fu_540_p3) > signed(phase_reg_1288_pp0_iter1_reg)) else "0";
    icmp_ln84_1_fu_588_p2 <= "1" when (sinces_since_1_reg_1304 = ap_const_lv8_0) else "0";
    icmp_ln84_2_fu_625_p2 <= "1" when (sinces_since_2_reg_1312 = ap_const_lv8_0) else "0";
    icmp_ln84_3_fu_662_p2 <= "1" when (sinces_since_3_reg_1320 = ap_const_lv8_0) else "0";
    icmp_ln84_fu_552_p2 <= "1" when (sinces_since_reg_1296 = ap_const_lv8_0) else "0";
    icmp_ln91_1_fu_839_p2 <= "0" when (sinces_since_1_reg_1304_pp0_iter2_reg = ap_const_lv8_1) else "1";
    icmp_ln91_2_fu_910_p2 <= "0" when (sinces_since_2_reg_1312_pp0_iter2_reg = ap_const_lv8_1) else "1";
    icmp_ln91_3_fu_981_p2 <= "0" when (sinces_since_3_reg_1320_pp0_iter2_reg = ap_const_lv8_1) else "1";
    icmp_ln91_fu_768_p2 <= "0" when (sinces_since_reg_1296_pp0_iter2_reg = ap_const_lv8_1) else "1";

    instream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, instream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            instream_TDATA_blk_n <= instream_TVALID_int_regslice;
        else 
            instream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    instream_TREADY <= regslice_both_instream_V_data_V_U_ack_in;

    instream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            instream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            instream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    last_group_fu_535_p2 <= std_logic_vector(unsigned(tmp_user_V_1_reg_1252_pp0_iter1_reg) + unsigned(ap_const_lv9_1FF));
    new_since_1_fu_598_p2 <= std_logic_vector(unsigned(sinces_since_1_reg_1304) + unsigned(ap_const_lv8_FF));
    new_since_2_fu_635_p2 <= std_logic_vector(unsigned(sinces_since_2_reg_1312) + unsigned(ap_const_lv8_FF));
    new_since_3_fu_672_p2 <= std_logic_vector(unsigned(sinces_since_3_reg_1320) + unsigned(ap_const_lv8_FF));
    new_since_fu_561_p2 <= std_logic_vector(unsigned(sinces_since_reg_1296) + unsigned(ap_const_lv8_FF));
    or_ln91_1_fu_844_p2 <= (trig_1_fu_835_p2 or icmp_ln91_1_fu_839_p2);
    or_ln91_2_fu_915_p2 <= (trig_2_fu_906_p2 or icmp_ln91_2_fu_910_p2);
    or_ln91_3_fu_986_p2 <= (trig_3_fu_977_p2 or icmp_ln91_3_fu_981_p2);
    or_ln91_fu_773_p2 <= (trig_fu_764_p2 or icmp_ln91_fu_768_p2);

    outstream_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, outstream_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            outstream_TDATA_blk_n <= outstream_TREADY_int_regslice;
        else 
            outstream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outstream_TUSER_int_regslice <= ((((trig_3_reg_1596 & trig_2_reg_1577) & trig_1_reg_1558) & trig_reg_1539) & tmp_user_V_1_reg_1252_pp0_iter3_reg);
    outstream_TVALID <= regslice_both_outstream_V_data_V_U_vld_out;

    outstream_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            outstream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            outstream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    phase_1_fu_566_p4 <= tmp_data_V_reg_1244_pp0_iter1_reg(31 downto 16);
    phase_2_fu_603_p4 <= tmp_data_V_reg_1244_pp0_iter1_reg(47 downto 32);
    phase_3_fu_640_p4 <= tmp_data_V_reg_1244_pp0_iter1_reg(63 downto 48);
    phase_fu_349_p1 <= instream_TDATA_int_regslice(16 - 1 downto 0);
    photon_data_address0 <= zext_ln587_fu_677_p1(9 - 1 downto 0);
    photon_data_address1 <= zext_ln587_1_fu_342_p1(9 - 1 downto 0);

    photon_data_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            photon_data_ce0 <= ap_const_logic_1;
        else 
            photon_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    photon_data_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            photon_data_ce1 <= ap_const_logic_1;
        else 
            photon_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    photon_data_d0 <= (((((((photon_cache_lane_phase_3 & photon_cache_lane_time) & photon_cache_lane_phase) & photon_cache_lane_time_1) & photon_cache_lane_phase_1) & photon_cache_lane_time_2) & photon_cache_lane_phase_2) & photon_cache_lane_time_3);

    photon_data_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            photon_data_we0 <= ap_const_logic_1;
        else 
            photon_data_we0 <= ap_const_logic_0;
        end if; 
    end process;


    photon_fifos_0_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, or_ln91_reg_1544, or_ln91_reg_1544_pp0_iter4_reg, photon_fifos_0_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_reg_1544_pp0_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_reg_1544 = ap_const_lv1_0)))) then 
            photon_fifos_0_TDATA_blk_n <= photon_fifos_0_TREADY_int_regslice;
        else 
            photon_fifos_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    photon_fifos_0_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_1135_p5),64));
    photon_fifos_0_TVALID <= regslice_both_photon_fifos_0_U_vld_out;

    photon_fifos_0_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, or_ln91_reg_1544, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln91_reg_1544 = ap_const_lv1_0))) then 
            photon_fifos_0_TVALID_int_regslice <= ap_const_logic_1;
        else 
            photon_fifos_0_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    photon_fifos_1_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, or_ln91_1_reg_1563, or_ln91_1_reg_1563_pp0_iter4_reg, photon_fifos_1_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_1_reg_1563_pp0_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_1_reg_1563 = ap_const_lv1_0)))) then 
            photon_fifos_1_TDATA_blk_n <= photon_fifos_1_TREADY_int_regslice;
        else 
            photon_fifos_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    photon_fifos_1_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_1164_p4),64));
    photon_fifos_1_TVALID <= regslice_both_photon_fifos_1_U_vld_out;

    photon_fifos_1_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, or_ln91_1_reg_1563, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln91_1_reg_1563 = ap_const_lv1_0))) then 
            photon_fifos_1_TVALID_int_regslice <= ap_const_logic_1;
        else 
            photon_fifos_1_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    photon_fifos_2_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, or_ln91_2_reg_1582, or_ln91_2_reg_1582_pp0_iter4_reg, photon_fifos_2_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_2_reg_1582_pp0_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_2_reg_1582 = ap_const_lv1_0)))) then 
            photon_fifos_2_TDATA_blk_n <= photon_fifos_2_TREADY_int_regslice;
        else 
            photon_fifos_2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    photon_fifos_2_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_1192_p4),64));
    photon_fifos_2_TVALID <= regslice_both_photon_fifos_2_U_vld_out;

    photon_fifos_2_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, or_ln91_2_reg_1582, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln91_2_reg_1582 = ap_const_lv1_0))) then 
            photon_fifos_2_TVALID_int_regslice <= ap_const_logic_1;
        else 
            photon_fifos_2_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    photon_fifos_3_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, or_ln91_3_reg_1601, or_ln91_3_reg_1601_pp0_iter4_reg, photon_fifos_3_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_3_reg_1601_pp0_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln91_3_reg_1601 = ap_const_lv1_0)))) then 
            photon_fifos_3_TDATA_blk_n <= photon_fifos_3_TREADY_int_regslice;
        else 
            photon_fifos_3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    photon_fifos_3_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_1220_p4),64));
    photon_fifos_3_TVALID <= regslice_both_photon_fifos_3_U_vld_out;

    photon_fifos_3_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, or_ln91_3_reg_1601, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln91_3_reg_1601 = ap_const_lv1_0))) then 
            photon_fifos_3_TVALID_int_regslice <= ap_const_logic_1;
        else 
            photon_fifos_3_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    photon_out_id_V_1_fu_1150_p2 <= (photon_out_id_V_fu_1120_p3 or ap_const_lv11_1);
    photon_out_id_V_2_fu_1178_p2 <= (photon_out_id_V_fu_1120_p3 or ap_const_lv11_2);
    photon_out_id_V_3_fu_1206_p2 <= (photon_out_id_V_fu_1120_p3 or ap_const_lv11_3);
    photon_out_id_V_fu_1120_p3 <= (tmp_user_V_1_reg_1252_pp0_iter3_reg & ap_const_lv2_0);
    photon_out_time_V_1_fu_1159_p2 <= std_logic_vector(unsigned(tmp_reg_1265_pp0_iter3_reg) - unsigned(zext_ln232_1_fu_1156_p1));
    photon_out_time_V_2_fu_1187_p2 <= std_logic_vector(unsigned(tmp_reg_1265_pp0_iter3_reg) - unsigned(zext_ln232_2_fu_1184_p1));
    photon_out_time_V_3_fu_1215_p2 <= std_logic_vector(unsigned(tmp_reg_1265_pp0_iter3_reg) - unsigned(zext_ln232_3_fu_1212_p1));
    photon_out_time_V_fu_1130_p2 <= std_logic_vector(unsigned(tmp_reg_1265_pp0_iter3_reg) - unsigned(zext_ln232_fu_1127_p1));
    photons_lane_phase_12_fu_784_p3 <= 
        phase_reg_1288_pp0_iter2_reg when (update_photon_reg_1440(0) = '1') else 
        photons_lane_phase_reg_1334_pp0_iter2_reg;
    photons_lane_phase_13_fu_828_p3 <= 
        photons_lane_phase_reg_1334_pp0_iter2_reg when (xor_ln84_fu_795_p2(0) = '1') else 
        select_ln84_4_fu_821_p3;
    photons_lane_phase_14_fu_855_p3 <= 
        phase_1_reg_1452 when (update_photon_1_reg_1469(0) = '1') else 
        photons_lane_phase_1_reg_1347_pp0_iter2_reg;
    photons_lane_phase_15_fu_899_p3 <= 
        photons_lane_phase_1_reg_1347_pp0_iter2_reg when (xor_ln84_1_fu_866_p2(0) = '1') else 
        select_ln84_10_fu_892_p3;
    photons_lane_phase_16_fu_926_p3 <= 
        phase_2_reg_1481 when (update_photon_2_reg_1498(0) = '1') else 
        photons_lane_phase_2_reg_1360_pp0_iter2_reg;
    photons_lane_phase_17_fu_970_p3 <= 
        photons_lane_phase_2_reg_1360_pp0_iter2_reg when (xor_ln84_2_fu_937_p2(0) = '1') else 
        select_ln84_16_fu_963_p3;
    photons_lane_phase_18_fu_997_p3 <= 
        phase_3_reg_1510 when (update_photon_3_reg_1527(0) = '1') else 
        photons_lane_phase_3_reg_1373_pp0_iter2_reg;
    photons_lane_phase_19_fu_1041_p3 <= 
        photons_lane_phase_3_reg_1373_pp0_iter2_reg when (xor_ln84_3_fu_1008_p2(0) = '1') else 
        select_ln84_22_fu_1034_p3;
    photons_lane_time_10_fu_992_p3 <= 
        new_since_3_reg_1533 when (update_photon_3_reg_1527(0) = '1') else 
        photons_lane_time_3_reg_1367_pp0_iter2_reg;
    photons_lane_time_11_fu_1027_p3 <= 
        photons_lane_time_3_reg_1367_pp0_iter2_reg when (xor_ln84_3_fu_1008_p2(0) = '1') else 
        select_ln84_20_fu_1020_p3;
    photons_lane_time_4_fu_779_p3 <= 
        new_since_reg_1446 when (update_photon_reg_1440(0) = '1') else 
        photons_lane_time_reg_1328_pp0_iter2_reg;
    photons_lane_time_5_fu_814_p3 <= 
        photons_lane_time_reg_1328_pp0_iter2_reg when (xor_ln84_fu_795_p2(0) = '1') else 
        select_ln84_2_fu_807_p3;
    photons_lane_time_6_fu_850_p3 <= 
        new_since_1_reg_1475 when (update_photon_1_reg_1469(0) = '1') else 
        photons_lane_time_1_reg_1341_pp0_iter2_reg;
    photons_lane_time_7_fu_885_p3 <= 
        photons_lane_time_1_reg_1341_pp0_iter2_reg when (xor_ln84_1_fu_866_p2(0) = '1') else 
        select_ln84_8_fu_878_p3;
    photons_lane_time_8_fu_921_p3 <= 
        new_since_2_reg_1504 when (update_photon_2_reg_1498(0) = '1') else 
        photons_lane_time_2_reg_1354_pp0_iter2_reg;
    photons_lane_time_9_fu_956_p3 <= 
        photons_lane_time_2_reg_1354_pp0_iter2_reg when (xor_ln84_2_fu_937_p2(0) = '1') else 
        select_ln84_14_fu_949_p3;
    photons_lane_time_fu_387_p1 <= photon_data_q1(8 - 1 downto 0);
    select_ln84_10_fu_892_p3 <= 
        phase_1_reg_1452 when (trig_1_fu_835_p2(0) = '1') else 
        photons_lane_phase_14_fu_855_p3;
    select_ln84_12_fu_931_p3 <= 
        hoffs_2_reg_1392_pp0_iter2_reg when (trig_2_fu_906_p2(0) = '1') else 
        new_since_2_reg_1504;
    select_ln84_14_fu_949_p3 <= 
        hoffs_2_reg_1392_pp0_iter2_reg when (trig_2_fu_906_p2(0) = '1') else 
        photons_lane_time_8_fu_921_p3;
    select_ln84_16_fu_963_p3 <= 
        phase_2_reg_1481 when (trig_2_fu_906_p2(0) = '1') else 
        photons_lane_phase_16_fu_926_p3;
    select_ln84_18_fu_1002_p3 <= 
        hoffs_3_reg_1398_pp0_iter2_reg when (trig_3_fu_977_p2(0) = '1') else 
        new_since_3_reg_1533;
    select_ln84_20_fu_1020_p3 <= 
        hoffs_3_reg_1398_pp0_iter2_reg when (trig_3_fu_977_p2(0) = '1') else 
        photons_lane_time_10_fu_992_p3;
    select_ln84_22_fu_1034_p3 <= 
        phase_3_reg_1510 when (trig_3_fu_977_p2(0) = '1') else 
        photons_lane_phase_18_fu_997_p3;
    select_ln84_2_fu_807_p3 <= 
        hoffs_reg_1380_pp0_iter2_reg when (trig_fu_764_p2(0) = '1') else 
        photons_lane_time_4_fu_779_p3;
    select_ln84_4_fu_821_p3 <= 
        phase_reg_1288_pp0_iter2_reg when (trig_fu_764_p2(0) = '1') else 
        photons_lane_phase_12_fu_784_p3;
    select_ln84_6_fu_860_p3 <= 
        hoffs_1_reg_1386_pp0_iter2_reg when (trig_1_fu_835_p2(0) = '1') else 
        new_since_1_reg_1475;
    select_ln84_8_fu_878_p3 <= 
        hoffs_1_reg_1386_pp0_iter2_reg when (trig_1_fu_835_p2(0) = '1') else 
        photons_lane_time_6_fu_850_p3;
    select_ln84_fu_789_p3 <= 
        hoffs_reg_1380_pp0_iter2_reg when (trig_fu_764_p2(0) = '1') else 
        new_since_reg_1446;
    shl_ln884_1_fu_575_p3 <= (tmp_1_reg_1409 & ap_const_lv8_0);
    shl_ln884_2_fu_612_p3 <= (tmp_3_reg_1414 & ap_const_lv8_0);
    shl_ln884_3_fu_649_p3 <= (tmp_4_reg_1419 & ap_const_lv8_0);
    shl_ln_fu_540_p3 <= (trunc_ln884_reg_1404 & ap_const_lv8_0);
    since_data_address0 <= zext_ln587_fu_677_p1(9 - 1 downto 0);
    since_data_address1 <= zext_ln587_1_fu_342_p1(9 - 1 downto 0);

    since_data_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            since_data_ce0 <= ap_const_logic_1;
        else 
            since_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    since_data_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            since_data_ce1 <= ap_const_logic_1;
        else 
            since_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    since_data_d0 <= (((since_cache_since & since_cache_since_1) & since_cache_since_2) & since_cache_since_3);

    since_data_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            since_data_we0 <= ap_const_logic_1;
        else 
            since_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sinces_since_11_fu_1013_p3 <= 
        sinces_since_3_reg_1320_pp0_iter2_reg when (xor_ln84_3_fu_1008_p2(0) = '1') else 
        select_ln84_18_fu_1002_p3;
    sinces_since_5_fu_800_p3 <= 
        sinces_since_reg_1296_pp0_iter2_reg when (xor_ln84_fu_795_p2(0) = '1') else 
        select_ln84_fu_789_p3;
    sinces_since_7_fu_871_p3 <= 
        sinces_since_1_reg_1304_pp0_iter2_reg when (xor_ln84_1_fu_866_p2(0) = '1') else 
        select_ln84_6_fu_860_p3;
    sinces_since_9_fu_942_p3 <= 
        sinces_since_2_reg_1312_pp0_iter2_reg when (xor_ln84_2_fu_937_p2(0) = '1') else 
        select_ln84_12_fu_931_p3;
    sinces_since_fu_353_p1 <= since_data_q1(8 - 1 downto 0);
    threshoffs_address0 <= zext_ln587_1_fu_342_p1(9 - 1 downto 0);

    threshoffs_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            threshoffs_ce0 <= ap_const_logic_1;
        else 
            threshoffs_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    timestamp_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, timestamp_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            timestamp_TDATA_blk_n <= timestamp_TVALID_int_regslice;
        else 
            timestamp_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    timestamp_TREADY <= regslice_both_timestamp_U_ack_in;

    timestamp_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            timestamp_TREADY_int_regslice <= ap_const_logic_1;
        else 
            timestamp_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_fu_1135_p5 <= (((tmp_user_V_1_reg_1252_pp0_iter3_reg & ap_const_lv2_0) & photons_lane_phase_13_reg_1553) & photon_out_time_V_fu_1130_p2);
    tmp_5_fu_1164_p4 <= ((photon_out_id_V_1_fu_1150_p2 & photons_lane_phase_15_reg_1572) & photon_out_time_V_1_fu_1159_p2);
    tmp_8_fu_1192_p4 <= ((photon_out_id_V_2_fu_1178_p2 & photons_lane_phase_17_reg_1591) & photon_out_time_V_2_fu_1187_p2);
    tmp_fu_338_p1 <= timestamp_TDATA_int_regslice(36 - 1 downto 0);
    tmp_s_fu_1220_p4 <= ((photon_out_id_V_3_fu_1206_p2 & photons_lane_phase_19_reg_1610) & photon_out_time_V_3_fu_1215_p2);
    trig_1_fu_835_p2 <= (icmp_ln84_1_reg_1463 and icmp_ln1696_1_reg_1458);
    trig_2_fu_906_p2 <= (icmp_ln84_2_reg_1492 and icmp_ln1696_2_reg_1487);
    trig_3_fu_977_p2 <= (icmp_ln84_3_reg_1521 and icmp_ln1696_3_reg_1516);
    trig_fu_764_p2 <= (icmp_ln84_reg_1434 and icmp_ln1696_reg_1429);
    trunc_ln884_fu_501_p1 <= threshoffs_q0(8 - 1 downto 0);
    update_photon_1_fu_593_p2 <= "1" when (signed(phase_1_fu_566_p4) < signed(photons_lane_phase_1_reg_1347)) else "0";
    update_photon_2_fu_630_p2 <= "1" when (signed(phase_2_fu_603_p4) < signed(photons_lane_phase_2_reg_1360)) else "0";
    update_photon_3_fu_667_p2 <= "1" when (signed(phase_3_fu_640_p4) < signed(photons_lane_phase_3_reg_1373)) else "0";
    update_photon_fu_557_p2 <= "1" when (signed(phase_reg_1288_pp0_iter1_reg) < signed(photons_lane_phase_reg_1334)) else "0";
    xor_ln84_1_fu_866_p2 <= (trig_1_fu_835_p2 xor icmp_ln84_1_reg_1463);
    xor_ln84_2_fu_937_p2 <= (trig_2_fu_906_p2 xor icmp_ln84_2_reg_1492);
    xor_ln84_3_fu_1008_p2 <= (trig_3_fu_977_p2 xor icmp_ln84_3_reg_1521);
    xor_ln84_fu_795_p2 <= (trig_fu_764_p2 xor icmp_ln84_reg_1434);
    zext_ln232_1_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(photons_lane_time_6_reg_1567),36));
    zext_ln232_2_fu_1184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(photons_lane_time_8_reg_1586),36));
    zext_ln232_3_fu_1212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(photons_lane_time_10_reg_1605),36));
    zext_ln232_fu_1127_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(photons_lane_time_4_reg_1548),36));
    zext_ln587_1_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(instream_TUSER_int_regslice),64));
    zext_ln587_fu_677_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(last_group_reg_1424),64));
end behav;
